# Generated by Django 5.2.3 on 2026-01-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="deliverable",
            field=models.CharField(
                choices=[
                    ("invitation_card", "Carte d’invitation"),
                    ("poster", "Affiche"),
                    ("calendar", "Calendrier"),
                    ("flyer", "Flyer"),
                    ("banner", "Bannière"),
                    ("logo", "Logo"),
                    ("brochure", "Brochure"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=30,
                verbose_name="Livrable",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("digital", "Service numérique"),
                    ("design", "Design / Graphisme"),
                    ("print", "Impression / Supports"),
                    ("event", "Événementiel"),
                    ("maintenance", "Maintenance / Support"),
                    ("other", "Autre"),
                ],
                default="digital",
                max_length=20,
                verbose_name="Type de service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="turnaround_days",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Délai estimé de livraison.",
                verbose_name="Délai (jours)",
            ),
        ),
    ]
