# Generated by Django 5.2.3 on 2026-01-22 18:07

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_service_deliverable_service_service_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "quote_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-généré si vide.",
                        max_length=32,
                        null=True,
                        unique=True,
                        verbose_name="Numéro de devis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("rejected", "Refusé"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("admin", "Admin"),
                            ("email", "Email"),
                            ("phone", "Téléphone"),
                            ("other", "Autre"),
                        ],
                        db_index=True,
                        default="admin",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Nom client"
                    ),
                ),
                (
                    "client_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email client"
                    ),
                ),
                (
                    "client_phone",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Téléphone client"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Entreprise"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=80, verbose_name="Pays"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Ville"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Objet"),
                ),
                (
                    "message",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Message / Besoin client"
                    ),
                ),
                (
                    "terms",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Conditions / Modalités"
                    ),
                ),
                (
                    "internal_notes",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Notes internes"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "EUR"), ("XOF", "XOF")],
                        default="EUR",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Ex: 18.00 pour 18%.",
                        max_digits=6,
                        verbose_name="TVA (%)",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Sous-total",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Remises",
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="TVA",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Émis le"),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valide jusqu’au"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_override",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Titre (override)"
                    ),
                ),
                (
                    "description_override",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Description (override)"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Ex: 10.00 pour 10%.",
                        max_digits=6,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=100, verbose_name="Ordre"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Ligne de devis",
                "verbose_name_plural": "Lignes de devis",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=220, verbose_name="Élément")),
                (
                    "order",
                    models.PositiveIntegerField(default=100, verbose_name="Ordre"),
                ),
            ],
            options={
                "verbose_name": "Service — Feature",
                "verbose_name_plural": "Service — Features",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackageFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=220, verbose_name="Élément")),
                (
                    "is_highlight",
                    models.BooleanField(
                        default=False, verbose_name="Mettre en évidence"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=100, verbose_name="Ordre"),
                ),
            ],
            options={
                "verbose_name": "Pack — Feature",
                "verbose_name_plural": "Pack — Features",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="icon",
            field=models.CharField(
                blank=True,
                default="fa-solid fa-layer-group",
                help_text="Ex: fa-solid fa-cloud, fa-solid fa-shield-halved",
                max_length=80,
                verbose_name="Icône (FontAwesome)",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Ordre d’affichage"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publié le"),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="billing_period",
            field=models.CharField(
                choices=[
                    ("yearly", "Annuel"),
                    ("monthly", "Mensuel"),
                    ("one_time", "Ponctuel"),
                    ("custom", "Sur devis"),
                ],
                default="yearly",
                max_length=16,
                verbose_name="Périodicité",
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "EUR"), ("XOF", "XOF")],
                default="EUR",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="emails_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre d’e-mails pro"
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="included_domain_year",
            field=models.BooleanField(
                default=False, verbose_name="Nom de domaine (1 an) inclus"
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="included_ssl",
            field=models.BooleanField(default=True, verbose_name="SSL inclus"),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="max_pages",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Pages max (si applicable)"
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="order",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Ordre d’affichage"
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="support_level",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("priority", "Prioritaire"),
                    ("dedicated", "Dédié"),
                ],
                default="standard",
                max_length=16,
                verbose_name="Support",
            ),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="tier",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("business", "Business"),
                    ("premium", "Premium"),
                    ("custom", "Sur mesure"),
                ],
                default="starter",
                max_length=16,
                verbose_name="Niveau",
            ),
        ),
        migrations.AddField(
            model_name="servicepackagetranslation",
            name="cta_label",
            field=models.CharField(
                blank=True,
                default="Demander un devis",
                max_length=40,
                verbose_name="Libellé du bouton (CTA)",
            ),
        ),
        migrations.AddField(
            model_name="servicepackagetranslation",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="SEO description"
            ),
        ),
        migrations.AddField(
            model_name="servicepackagetranslation",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="SEO title"),
        ),
        migrations.AddField(
            model_name="servicepackagetranslation",
            name="tagline",
            field=models.CharField(blank=True, max_length=220, verbose_name="Accroche"),
        ),
        migrations.AddField(
            model_name="servicetranslation",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="SEO description"
            ),
        ),
        migrations.AddField(
            model_name="servicetranslation",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="SEO title"),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("design", "Design & Communication"),
                    ("cloud", "Hébergement, Cloud & Infrastructure"),
                    ("dev", "Développement Web & Logiciels"),
                    ("automation", "Automatisation & Digitalisation"),
                    ("managed", "Maintenance IT & Infogérance"),
                    ("security", "Sécurité & Sauvegardes"),
                    ("digital", "Service numérique"),
                    ("print", "Impression / Supports"),
                    ("event", "Événementiel"),
                    ("maintenance", "Maintenance / Support"),
                    ("other", "Autre"),
                ],
                default="digital",
                max_length=20,
                verbose_name="Type de service",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="services_se_is_acti_39af20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["service_type", "deliverable"],
                name="services_se_service_ec120a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepackage",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="services_se_is_acti_7960e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicepackage",
            index=models.Index(
                fields=["tier", "billing_period", "currency"],
                name="services_se_tier_6f2667_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["status", "is_active", "created_at"],
                name="services_qu_status_6e6796_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["currency", "created_at"], name="services_qu_currenc_610d1b_idx"
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_lines",
                to="services.servicepackage",
                verbose_name="Pack",
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="services.quote",
                verbose_name="Devis",
            ),
        ),
        migrations.AddField(
            model_name="quoteline",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quote_lines",
                to="services.service",
                verbose_name="Service",
            ),
        ),
        migrations.AddField(
            model_name="servicefeature",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="services.service",
            ),
        ),
        migrations.AddField(
            model_name="servicepackagefeature",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="services.servicepackage",
            ),
        ),
        migrations.AddIndex(
            model_name="quoteline",
            index=models.Index(
                fields=["quote", "order"], name="services_qu_quote_i_c52dfe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("service__isnull", False), ("package__isnull", True)),
                    models.Q(("service__isnull", True), ("package__isnull", False)),
                    models.Q(("service__isnull", True), ("package__isnull", True)),
                    _connector="OR",
                ),
                name="quote_line_one_ref_or_none",
            ),
        ),
        migrations.AddIndex(
            model_name="servicefeature",
            index=models.Index(
                fields=["service", "order"], name="services_se_service_dbccc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicepackagefeature",
            index=models.Index(
                fields=["package", "order"], name="services_se_package_93899d_idx"
            ),
        ),
    ]
