import os
from textwrap import dedent

# 0. Chemin racine de la librairie SCSS
BASE_DIR = "scss"

# 1. Dictionnaire : dossier → fichiers SCSS
folders = {
    "0-settings": ["_breakpoints.scss", "_z-index.scss"],
    "1-import": ["_variables.scss", "_mixins.scss"],
    "2-tools": ["_normalize.scss", "_functions.scss", "_helpers.scss", "_reset.scss"],
    "3-generic": ["_typography.scss"],
    "4-elements": [
        "_body.scss",
        "_header.scss",
        "_links.scss",
        "_lists.scss",
        "_box-sizing.scss",
    ],
    "5-grid": ["_containers.scss", "_grid.scss", "_utilities.scss"],
    "6-layout": ["_base.scss", "_footer.scss", "_main.scss", "_soci.scss"],
    "7-components": [
        "_buttons.scss",
        "_forms.scss",
        "_cards.scss",
        "_navbar.scss",
        "_nav.scss",
        "_topbar.scss",
        "_breadcrumbs.scss",
        "_pagination.scss",
        "_badges.scss",
        "_alerts.scss",
        "_modals.scss",
        "_carousel.scss",
        "_accordion.scss",
        "_avatars.scss",
        "_tooltips.scss",
        "_dropdowns.scss",
        "_inputs.scss",
        "_sidebars.scss",
        "_tables.scss",
        "_media.scss",
        "_timeline.scss",
        "_toasts.scss",
        "_tabs.scss",
        "_progress.scss",
    ],
    "8-animations": ["_animations.scss", "_transitions.scss"],
    "9-icons": ["_icons.scss"],
    "10-utilities": [
        "_display.scss",
        "_position.scss",
        "_sizing.scss",
        "_visibility.scss",
        "_accessibility.scss",
        "_flex.scss",
        "_align.scss",
        "_background.scss",
        "_borders.scss",
        "_colors.scss",
        "_float.scss",
        "_font.scss",
        "_height.scss",
        "_margin.scss",
        "_opacity.scss",
        "_overflow.scss",
        "_padding.scss",
        "_shadows.scss",
        "_spacing.scss",
        "_text.scss",
        "_transform.scss",
        "_width.scss",
    ],
    "11-themes": ["_default.scss", "_dark.scss", "_custom.scss", "_high-contrast.scss"],
    "12-responsive": ["_responsive.scss"],
    "13-accessibility": [
        "_focus.scss",
        "_skip-links.scss",
        "_aria.scss",
        "_contrast.scss",
    ],
    "14-fixes": ["_browser.scss", "_polyfills.scss"],
    # 🔥 15-fontawesome exclu de la génération de fichiers
}

# 2. Création des dossiers et fichiers (hors librairies externes)
for folder, files in folders.items():
    dir_path = os.path.join(BASE_DIR, folder)
    os.makedirs(dir_path, exist_ok=True)

    for filename in files:
        file_path = os.path.join(dir_path, filename)
        if not os.path.exists(file_path):
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(f"// {folder}/{filename} — autogenerated placeholder\n\n")

# 3. Génération de main.scss
main_scss = dedent(
    """\
// main.scss — point d’entrée du framework

// 0. Configuration de base
@use 'settings/breakpoints';
@use 'settings/z-index';

// 1. import
@use 'import/variables'   as vars;
@use 'import/mixins'      as mix;

// 2. Normalisation et réinitialisation
@use 'tools/normalize';
@use 'tools/functions';
@use 'tools/helpers';
@use 'tools/reset';

// 3. generic
@use 'generic/typography';

// 4. Éléments
@use 'elements/body';
@use 'elements/header';
@use 'elements/links';
@use 'elements/lists';
@use 'elements/box-sizing';

// 5. Système de grille
@use 'grid/containers';
@use 'grid/grid';
@use 'grid/utilities';

// 6. Layout
@use 'layout/base';
@use 'layout/footer';
@use 'layout/main';
@use 'layout/soci';

// 7. Composants d’interface
@use 'components/buttons';
@use 'components/forms';
@use 'components/cards';
@use 'components/navbar';
@use 'components/nav';
@use 'components/topbar';
@use 'components/breadcrumbs';
@use 'components/pagination';
@use 'components/badges';
@use 'components/alerts';
@use 'components/modals';
@use 'components/carousel';
@use 'components/accordion';
@use 'components/avatars';
@use 'components/tooltips';
@use 'components/dropdowns';
@use 'components/inputs';
@use 'components/sidebars';
@use 'components/tables';
@use 'components/media';
@use 'components/timeline';
@use 'components/toasts';
@use 'components/tabs';
@use 'components/progress';

// 8. Animations et transitions
@use 'animations/animations';
@use 'animations/transitions';

// 9. Icônes
@use 'icons/icons';

// 10. Classes utilitaires
@use 'utilities/display';
@use 'utilities/position';
@use 'utilities/sizing';
@use 'utilities/visibility';
@use 'utilities/accessibility';
@use 'utilities/flex';
@use 'utilities/align';
@use 'utilities/background';
@use 'utilities/borders';
@use 'utilities/colors';
@use 'utilities/float';
@use 'utilities/font';
@use 'utilities/height';
@use 'utilities/margin';
@use 'utilities/opacity';
@use 'utilities/overflow';
@use 'utilities/padding';
@use 'utilities/shadows';
@use 'utilities/spacing';
@use 'utilities/text';
@use 'utilities/transform';
@use 'utilities/width';

// 11. Thèmes et personnalisation
@use 'themes/default';
@use 'themes/dark';
@use 'themes/custom';
@use 'themes/high-contrast';

// 12. Responsive / Media Queries
@use 'responsive/responsive';

// 13. Accessibilité
@use 'accessibility/focus';
@use 'accessibility/skip-links';
@use 'accessibility/aria';
@use 'accessibility/contrast';

// 14. Correctifs et compatibilité
@use 'fixes/browser';
@use 'fixes/polyfills';

// 15. Librairies externes
@import 'fontawesome-free/css/all.min.css'; // CSS pur, on garde @import
@use 'bootstrap/scss/bootstrap';           // SCSS, si node_modules accessible
"""
)

main_path = os.path.join(BASE_DIR, "main.scss")
with open(main_path, "w", encoding="utf-8") as f:
    f.write(main_scss)

print(
    f"✅ Structure complète générée dans « {BASE_DIR} » avec 15 modules (lib externes exclues du build)."
)
