# pyproject.toml

[tool.black]
line-length = 88
target-version = ['py310']  # adapte à ta version Python
exclude = '''
/(
    \.git
  | \.venv
  | env
  | venv
  | build
  | dist
  | migrations
  | templates
  | .*\.html
)/
'''

[tool.isort]
profile = "black"
line_length = 88
skip_glob = ["*/templates/*", "*/migrations/*"]
known_django = ["django"]
sections = ["FUTURE", "STDLIB", "DJANGO", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.djlint]
# Ces lignes ne prennent effet que si tu installes djlint
indent = 2
format_js = true
format_css = true
ignore = "H031,H017"  # désactive des warnings courants (facultatif)
