# Generated by Django 5.2.3 on 2025-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b2b", "0001_initial"),
        ("ecommerce", "0006_invoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Entreprise",
                "verbose_name_plural": "Entreprises",
            },
        ),
        migrations.AlterModelOptions(
            name="companyuser",
            options={
                "verbose_name": "Utilisateur entreprise",
                "verbose_name_plural": "Utilisateurs entreprise",
            },
        ),
        migrations.AlterUniqueTogether(
            name="bulkorderitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="bulkorderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantité"),
        ),
        migrations.AddConstraint(
            model_name="bulkorderitem",
            constraint=models.UniqueConstraint(
                fields=("bulk_order", "product"), name="unique_product_per_bulk_order"
            ),
        ),
    ]
