# Generated by Django 5.2.3 on 2026-01-02 02:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b2b", "0002_alter_company_options_alter_companyuser_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "price_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Prix total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "delivery_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Délai (jours)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Soumise"),
                            ("SHORTLISTED", "Pré-sélectionnée"),
                            ("ACCEPTED", "Acceptée"),
                            ("REJECTED", "Rejetée"),
                            ("WITHDRAWN", "Retirée"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Offre",
                "verbose_name_plural": "Offres",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="RFQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=12,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=30, verbose_name="Unité"),
                ),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Budget min",
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Budget max",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Date limite"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("OPEN", "Ouvert"),
                            ("CLOSED", "Fermé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Demande de devis (RFQ)",
                "verbose_name_plural": "Demandes de devis (RFQ)",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ville"),
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(blank=True, max_length=2, verbose_name="Pays"),
        ),
        migrations.AddField(
            model_name="company",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="b2b_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Propriétaire",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PENDING", "En attente"),
                    ("SUSPENDED", "Suspendue"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, verbose_name="Site web"),
        ),
        migrations.AlterField(
            model_name="bulkorderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=14,
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="b2b.company",
                verbose_name="Entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("staff", "Employé"),
                    ("viewer", "Consultation"),
                ],
                default="viewer",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="b2b_company_name_973f33_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["status"], name="b2b_company_status_8ac18e_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active"], name="b2b_company_is_acti_a44a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["owner"], name="b2b_company_owner_i_7c7ee3_idx"),
        ),
        migrations.AddIndex(
            model_name="companyuser",
            index=models.Index(
                fields=["company"], name="b2b_company_company_5f24cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyuser",
            index=models.Index(fields=["user"], name="b2b_company_user_id_1139d2_idx"),
        ),
        migrations.AddIndex(
            model_name="companyuser",
            index=models.Index(fields=["role"], name="b2b_company_role_226d92_idx"),
        ),
        migrations.AddIndex(
            model_name="companyuser",
            index=models.Index(
                fields=["is_active"], name="b2b_company_is_acti_00073a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="companyuser",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_user_per_company"
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="b2b_offers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rfqs",
                to="b2b.company",
                verbose_name="Entreprise",
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="b2b_rfqs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Créé par",
            ),
        ),
        migrations.AddField(
            model_name="offer",
            name="rfq",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="b2b.rfq",
                verbose_name="RFQ",
            ),
        ),
        migrations.AddIndex(
            model_name="rfq",
            index=models.Index(fields=["company"], name="b2b_rfq_company_29692c_idx"),
        ),
        migrations.AddIndex(
            model_name="rfq",
            index=models.Index(fields=["status"], name="b2b_rfq_status_4e376e_idx"),
        ),
        migrations.AddIndex(
            model_name="rfq",
            index=models.Index(fields=["deadline"], name="b2b_rfq_deadlin_0d4e9c_idx"),
        ),
        migrations.AddIndex(
            model_name="rfq",
            index=models.Index(
                fields=["created_by"], name="b2b_rfq_created_de34c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["rfq"], name="b2b_offer_rfq_id_8e763e_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["supplier"], name="b2b_offer_supplie_b23ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["status"], name="b2b_offer_status_6cb976_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="offer",
            unique_together={("rfq", "supplier")},
        ),
    ]
