# Generated by Django 5.2.3 on 2026-01-02 19:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b2b", "0003_offer_rfq_company_address_company_city_and_more"),
        ("ecommerce", "0008_favorite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offer",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="companyuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                verbose_name="Montant",
            ),
        ),
        migrations.AddIndex(
            model_name="bulkorder",
            index=models.Index(
                fields=["company"], name="b2b_bulkord_company_b32e71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkorder",
            index=models.Index(fields=["status"], name="b2b_bulkord_status_e15e4d_idx"),
        ),
        migrations.AddIndex(
            model_name="bulkorder",
            index=models.Index(
                fields=["created_at"], name="b2b_bulkord_created_2573b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkorderitem",
            index=models.Index(
                fields=["bulk_order"], name="b2b_bulkord_bulk_or_4c01e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulkorderitem",
            index=models.Index(
                fields=["product"], name="b2b_bulkord_product_1789f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="b2b_invoice_status_e6034d_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["created_at"], name="b2b_invoice_created_95002f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="b2b_invoice_invoice_45218e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                fields=("rfq", "supplier"), name="unique_offer_per_rfq_supplier"
            ),
        ),
    ]
