# Generated by Django 5.2.3 on 2025-12-17 17:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("B2C", "B2C – Particulier"),
                            ("B2B", "B2B – Professionnel"),
                        ],
                        default="B2C",
                        max_length=3,
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix de base",
                    ),
                ),
                (
                    "promo_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix promotionnel",
                    ),
                ),
                ("promo_start", models.DateTimeField(blank=True, null=True)),
                ("promo_end", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=5, verbose_name="Devise"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="ecommerce.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarification produit",
                "verbose_name_plural": "Tarifications produits",
            },
        ),
        migrations.CreateModel(
            name="BulkPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantité minimale",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Prix unitaire",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_prices",
                        to="ecommerce.productpricing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prix dégressif",
                "verbose_name_plural": "Prix dégressifs",
                "ordering": ["min_quantity"],
            },
        ),
    ]
