# Generated by Django 5.2.3 on 2025-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Stock disponible"
            ),
        ),
    ]
