# Generated by Django 5.2.3 on 2025-12-29 14:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_cartitem_created_at_cartitem_unit_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ["id"],
                "verbose_name": "Article de commande",
                "verbose_name_plural": "Articles de commande",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mise à jour le"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Créé le",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Payée"),
                    ("shipped", "Expédiée"),
                    ("completed", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="ecommerce_o_status_27d41d_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_at"], name="ecommerce_o_created_86a742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="ecommerce_o_order_i_0ef8a4_idx"),
        ),
    ]
