# Generated by Django 5.2.3 on 2025-12-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_alter_orderitem_options_order_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_url",
            field=models.URLField(blank=True, verbose_name="URL de paiement"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="ecommerce.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("wave", "Wave"),
                    ("orange_money", "Orange Money"),
                ],
                db_index=True,
                max_length=20,
                verbose_name="Prestataire",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider_event_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID événement prestataire",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiée"),
                    ("pending", "En attente"),
                    ("succeeded", "Réussie"),
                    ("failed", "Échouée"),
                    ("cancelled", "Annulée"),
                ],
                db_index=True,
                default="initiated",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider", "status"], name="ecommerce_p_provide_0fe050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="ecommerce_p_created_df2d1a_idx"
            ),
        ),
    ]
