# Generated by Django 5.2.3 on 2025-12-31 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0006_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                help_text="Copie de l'email au moment de la commande (facture / export).",
                max_length=254,
                verbose_name="Email client",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="ecommerce_o_user_id_20253d_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer_email"], name="ecommerce_o_custome_7d6e10_idx"
            ),
        ),
    ]
