# Generated by Django 5.2.3 on 2026-01-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0008_favorite"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentTransaction",
            new_name="PaymentTransactions",
        ),
        migrations.RenameModel(
            old_name="ProductImage",
            new_name="ProductImages",
        ),
        migrations.RenameModel(
            old_name="ProductPricing",
            new_name="ProductsPricing",
        ),
        migrations.RenameIndex(
            model_name="paymenttransactions",
            new_name="ecommerce_p_provide_c26a96_idx",
            old_name="ecommerce_p_provide_0fe050_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransactions",
            new_name="ecommerce_p_created_dc1c08_idx",
            old_name="ecommerce_p_created_df2d1a_idx",
        ),
    ]
