# Generated by Django 5.2.3 on 2026-01-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0009_rename_paymenttransaction_paymenttransactions_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentTransactions",
            new_name="PaymentTransaction",
        ),
        migrations.RenameModel(
            old_name="ProductImages",
            new_name="ProductImage",
        ),
        migrations.RenameModel(
            old_name="ProductsPricing",
            new_name="ProductPricing",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="ecommerce_p_provide_0fe050_idx",
            old_name="ecommerce_p_provide_c26a96_idx",
        ),
        migrations.RenameIndex(
            model_name="paymenttransaction",
            new_name="ecommerce_p_created_df2d1a_idx",
            old_name="ecommerce_p_created_dc1c08_idx",
        ),
    ]
