# Generated by Django 5.2.3 on 2026-01-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0014_add_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant total"
            ),
        ),
    ]
