# Generated by Django 5.2.3 on 2026-01-24 12:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0015_alter_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkprice",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="categorytranslation",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Description SEO"
            ),
        ),
        migrations.AddField(
            model_name="categorytranslation",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Titre SEO"
            ),
        ),
        migrations.AddField(
            model_name="productpricing",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bulkprice",
            name="pricing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_prices",
                to="ecommerce.productpricing",
                verbose_name="Tarification",
            ),
        ),
        migrations.AlterField(
            model_name="bulkprice",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Prix unitaire",
            ),
        ),
        # migrations.AlterField(
        #     model_name="category",
        #     name="id",
        #     field=models.BigAutoField(primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name="categorytranslation",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Auto-généré si vide (par langue).",
                max_length=220,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Prix de base",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="currency",
            field=models.CharField(
                db_index=True,
                default="XOF",
                help_text="Ex: XOF, EUR, USD",
                max_length=5,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="pricing_type",
            field=models.CharField(
                choices=[("B2C", "B2C – Particulier"), ("B2B", "B2B – Professionnel")],
                db_index=True,
                default="B2C",
                max_length=3,
                verbose_name="Type de tarification",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing",
                to="ecommerce.product",
                verbose_name="Produit",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="promo_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin promo"),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="promo_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Prix promotionnel",
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="promo_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Début promo"
            ),
        ),
        migrations.AlterField(
            model_name="productpricing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddIndex(
            model_name="bulkprice",
            index=models.Index(
                fields=["pricing", "min_quantity"],
                name="ecommerce_b_pricing_4dcf97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active", "order"], name="ecommerce_c_is_acti_6a4c19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent", "order"], name="ecommerce_c_parent__6ff3aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(
                fields=["pricing_type", "currency"],
                name="ecommerce_p_pricing_91525c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(
                fields=["promo_start", "promo_end"],
                name="ecommerce_p_promo_s_9427cf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bulkprice",
            constraint=models.UniqueConstraint(
                fields=("pricing", "min_quantity"), name="uniq_bulkprice_pricing_minqty"
            ),
        ),
    ]
