# Generated by Django 5.2.3 on 2026-01-24 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_bulkprice_created_at_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_main", "sort_order", "id"],
                "verbose_name": "Image du produit",
                "verbose_name_plural": "Images du produit",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Plus petit = affiché en premier.",
                verbose_name="Ordre",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Description SEO"
            ),
        ),
        migrations.AddField(
            model_name="producttranslation",
            name="seo_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Titre SEO"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Mis en avant"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/%Y/%m/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_main",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Image principale"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_featured", "-created_at"],
                name="ecommerce_p_is_acti_570b85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="ecommerce_p_categor_c06f9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["vendor", "is_active"], name="ecommerce_p_vendor__4edd25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "-is_main", "sort_order"],
                name="ecommerce_p_product_155e35_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("product",),
                name="uniq_product_main_image",
            ),
        ),
    ]
