# Generated by Django 5.2.3 on 2026-01-24 17:17
from django.db import migrations, models


def _add_col_if_missing(table: str, column: str, ddl: str) -> str:
    return f"""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema='public'
      AND table_name='{table}'
      AND column_name='{column}'
  ) THEN
    {ddl};
  END IF;
END $$;
""".strip()


def _try(sql: str) -> str:
    return f"""
DO $$
BEGIN
  BEGIN
    {sql};
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;
""".strip()


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0018_db_hotfix_product_columns"),
    ]

    operations = [
        # fiche_technique
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=_add_col_if_missing(
                        "ecommerce_product",
                        "fiche_technique",
                        "ALTER TABLE ecommerce_product ADD COLUMN fiche_technique text NOT NULL DEFAULT ''",
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_try(
                        "ALTER TABLE ecommerce_product ALTER COLUMN fiche_technique SET DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="fiche_technique",
                    field=models.TextField(blank=True, verbose_name="Fiche technique"),
                ),
            ],
        ),
<<<<<<< HEAD

        # image (ImageField => varchar). Si déjà NOT NULL sur VPS, on drop NOT NULL.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=_add_col_if_missing(
                        "ecommerce_product",
                        "image",
                        "ALTER TABLE ecommerce_product ADD COLUMN image varchar(100) NULL",
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_try("ALTER TABLE ecommerce_product ALTER COLUMN image DROP NOT NULL"),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="image",
                    field=models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/main/%Y/%m/",
                        verbose_name="Image principale",
                    ),
                ),
            ],
=======
      	migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/main/%Y/%m/",
                verbose_name="Image principale",
            ),
>>>>>>> f44f2316 (fix migrations_019)
        ),

        # is_new
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=_add_col_if_missing(
                        "ecommerce_product",
                        "is_new",
                        "ALTER TABLE ecommerce_product ADD COLUMN is_new boolean NOT NULL DEFAULT false",
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_try("ALTER TABLE ecommerce_product ALTER COLUMN is_new SET DEFAULT false"),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="product",
                    name="is_new",
                    field=models.BooleanField(db_index=True, default=False, verbose_name="Nouveau"),
                ),
            ],
        ),

        # index (IF NOT EXISTS)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="CREATE INDEX IF NOT EXISTS ecommerce_p_is_new_3bcaab_idx ON ecommerce_product (is_new, is_active);",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name="product",
                    index=models.Index(
                        fields=["is_new", "is_active"],
                        name="ecommerce_p_is_new_3bcaab_idx",
                    ),
                ),
            ],
        ),
    ]
