# Generated by Django 5.2.3 on 2026-01-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0018_db_hotfix_product_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="fiche_technique",
            field=models.TextField(blank=True, verbose_name="Fiche technique"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/main/%Y/%m/",
                verbose_name="Image principale",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Nouveau"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_new", "is_active"], name="ecommerce_p_is_new_3bcaab_idx"
            ),
        ),
    ]
