# Generated manually (prod-safe) on 2026-01-25
from django.db import migrations


def _create_table_if_missing(table: str, ddl: str) -> str:
    return f"""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.tables
    WHERE table_schema='public' AND table_name='{table}'
  ) THEN
    {ddl}
  END IF;
END $$;
""".strip()


def _create_index_if_missing(indexname: str, ddl: str) -> str:
    return f"""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_indexes
    WHERE schemaname='public' AND indexname='{indexname}'
  ) THEN
    {ddl}
  END IF;
END $$;
""".strip()


def _try(sql: str) -> str:
    # Best-effort: ignore toute erreur (constraint déjà là, type différent, etc.)
    return f"""
DO $$
BEGIN
  BEGIN
    {sql}
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;
""".strip()


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0019_product_fiche_technique_product_image_more_safe"),
    ]

    operations = [
        # ============================================================
        # CART / CARTITEM (bloque souvent l'admin si manquant)
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_cart",
                """
CREATE TABLE ecommerce_cart (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_cart_user_id_idx",
                "CREATE INDEX ecommerce_cart_user_id_idx ON ecommerce_cart (user_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_cartitem",
                """
CREATE TABLE ecommerce_cartitem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id bigint NOT NULL,
  product_id bigint NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(12,2) NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_cartitem_cart_id_idx",
                "CREATE INDEX ecommerce_cartitem_cart_id_idx ON ecommerce_cartitem (cart_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_cartitem_product_id_idx",
                "CREATE INDEX ecommerce_cartitem_product_id_idx ON ecommerce_cartitem (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_cartitem
  ADD CONSTRAINT ecommerce_cartitem_cart_fk
  FOREIGN KEY (cart_id) REFERENCES ecommerce_cart(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_cartitem
  ADD CONSTRAINT ecommerce_cartitem_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ============================================================
        # WISHLIST / WISHLISTITEM
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_wishlist",
                """
CREATE TABLE ecommerce_wishlist (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_wishlist_user_id_idx",
                "CREATE INDEX ecommerce_wishlist_user_id_idx ON ecommerce_wishlist (user_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_wishlistitem",
                """
CREATE TABLE ecommerce_wishlistitem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wishlist_id bigint NOT NULL,
  product_id bigint NOT NULL,
  added_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_wishlistitem_wishlist_id_idx",
                "CREATE INDEX ecommerce_wishlistitem_wishlist_id_idx ON ecommerce_wishlistitem (wishlist_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_wishlistitem_product_id_idx",
                "CREATE INDEX ecommerce_wishlistitem_product_id_idx ON ecommerce_wishlistitem (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_wishlistitem
  ADD CONSTRAINT ecommerce_wishlistitem_wishlist_fk
  FOREIGN KEY (wishlist_id) REFERENCES ecommerce_wishlist(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_wishlistitem
  ADD CONSTRAINT ecommerce_wishlistitem_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ============================================================
        # REVIEW
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_review",
                """
CREATE TABLE ecommerce_review (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  user_id bigint NULL,
  rating integer NOT NULL DEFAULT 5,
  title varchar(255) NOT NULL DEFAULT '',
  content text NOT NULL DEFAULT '',
  is_approved boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_review_product_id_idx",
                "CREATE INDEX ecommerce_review_product_id_idx ON ecommerce_review (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_review
  ADD CONSTRAINT ecommerce_review_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ============================================================
        # PRODUCTIMAGE (si manquant)
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_productimage",
                """
CREATE TABLE ecommerce_productimage (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL,
  image varchar(100) NOT NULL DEFAULT '',
  alt_text varchar(255) NOT NULL DEFAULT '',
  is_main boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_productimage_product_id_idx",
                "CREATE INDEX ecommerce_productimage_product_id_idx ON ecommerce_productimage (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_productimage
  ADD CONSTRAINT ecommerce_productimage_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ============================================================
        # PRODUCTPRICING / BULKPRICE
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_productpricing",
                """
CREATE TABLE ecommerce_productpricing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL UNIQUE,
  pricing_type varchar(3) NOT NULL DEFAULT 'B2C',
  base_price numeric(12,2) NOT NULL DEFAULT 0,
  promo_price numeric(12,2) NULL,
  promo_start timestamptz NULL,
  promo_end timestamptz NULL,
  currency varchar(5) NOT NULL DEFAULT 'XOF',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_productpricing_product_id_idx",
                "CREATE INDEX ecommerce_productpricing_product_id_idx ON ecommerce_productpricing (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_productpricing
  ADD CONSTRAINT ecommerce_productpricing_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_bulkprice",
                """
CREATE TABLE ecommerce_bulkprice (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pricing_id bigint NOT NULL,
  min_quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(12,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_bulkprice_pricing_id_idx",
                "CREATE INDEX ecommerce_bulkprice_pricing_id_idx ON ecommerce_bulkprice (pricing_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_bulkprice
  ADD CONSTRAINT ecommerce_bulkprice_pricing_fk
  FOREIGN KEY (pricing_id) REFERENCES ecommerce_productpricing(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ============================================================
        # ORDER / ORDERITEM (si manquant)
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_order",
                """
CREATE TABLE ecommerce_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid varchar(36) NULL,
  user_id bigint NULL,
  status varchar(30) NOT NULL DEFAULT 'pending',
  total_amount numeric(12,2) NOT NULL DEFAULT 0,
  customer_email varchar(254) NULL,
  customer_phone varchar(50) NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_order_uuid_idx",
                "CREATE INDEX ecommerce_order_uuid_idx ON ecommerce_order (uuid);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_orderitem",
                """
CREATE TABLE ecommerce_orderitem (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL,
  product_id bigint NOT NULL,
  product_sku varchar(100) NOT NULL DEFAULT '',
  product_name varchar(255) NOT NULL DEFAULT '',
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric(12,2) NOT NULL DEFAULT 0
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_orderitem_order_id_idx",
                "CREATE INDEX ecommerce_orderitem_order_id_idx ON ecommerce_orderitem (order_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_orderitem_product_id_idx",
                "CREATE INDEX ecommerce_orderitem_product_id_idx ON ecommerce_orderitem (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_orderitem
  ADD CONSTRAINT ecommerce_orderitem_order_fk
  FOREIGN KEY (order_id) REFERENCES ecommerce_order(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_orderitem
  ADD CONSTRAINT ecommerce_orderitem_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE RESTRICT;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ============================================================
        # PAYMENTTRANSACTION / INVOICE / FAVORITE / SKUSEQUENCE / VENDOR
        # ============================================================
        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_paymenttransaction",
                """
CREATE TABLE ecommerce_paymenttransaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid varchar(36) NULL,
  order_id bigint NULL,
  provider varchar(30) NOT NULL DEFAULT '',
  status varchar(30) NOT NULL DEFAULT 'pending',
  amount numeric(12,2) NOT NULL DEFAULT 0,
  currency varchar(5) NOT NULL DEFAULT 'XOF',
  provider_payment_id varchar(255) NULL,
  payment_url text NULL,
  payload jsonb NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_paymenttransaction_uuid_idx",
                "CREATE INDEX ecommerce_paymenttransaction_uuid_idx ON ecommerce_paymenttransaction (uuid);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_paymenttransaction
  ADD CONSTRAINT ecommerce_paymenttransaction_order_fk
  FOREIGN KEY (order_id) REFERENCES ecommerce_order(id) ON DELETE SET NULL;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_invoice",
                """
CREATE TABLE ecommerce_invoice (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid varchar(36) NULL,
  order_id bigint NULL,
  file varchar(300) NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_invoice_uuid_idx",
                "CREATE INDEX ecommerce_invoice_uuid_idx ON ecommerce_invoice (uuid);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_favorite",
                """
CREATE TABLE ecommerce_favorite (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NULL,
  product_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_favorite_product_id_idx",
                "CREATE INDEX ecommerce_favorite_product_id_idx ON ecommerce_favorite (product_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_try(
                """
ALTER TABLE ecommerce_favorite
  ADD CONSTRAINT ecommerce_favorite_product_fk
  FOREIGN KEY (product_id) REFERENCES ecommerce_product(id) ON DELETE CASCADE;
"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_skusequence",
                """
CREATE TABLE ecommerce_skusequence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key varchar(50) NOT NULL UNIQUE,
  current integer NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RunSQL(
            sql=_create_table_if_missing(
                "ecommerce_vendor",
                """
CREATE TABLE ecommerce_vendor (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NULL,
  company_name varchar(255) NOT NULL DEFAULT '',
  is_verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
""",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=_create_index_if_missing(
                "ecommerce_vendor_user_id_idx",
                "CREATE INDEX ecommerce_vendor_user_id_idx ON ecommerce_vendor (user_id);",
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
