# Generated by Django 5.2.3 on 2026-01-25 02:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0019_product_fiche_technique_product_image_more_safe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkuSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vendor_code",
                    models.CharField(max_length=8, verbose_name="Code vendeur"),
                ),
                (
                    "category_code",
                    models.CharField(max_length=8, verbose_name="Code catégorie"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dernier numéro"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Séquence SKU",
                "verbose_name_plural": "Séquences SKU",
            },
        ),
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name": "Panier", "verbose_name_plural": "Paniers"},
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Favori",
                "verbose_name_plural": "Favoris",
            },
        ),
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
        migrations.AlterModelOptions(
            name="vendor",
            options={
                "ordering": ["-is_verified", "-is_active", "company_name"],
                "verbose_name": "Vendeur",
                "verbose_name_plural": "Vendeurs",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Liste de souhaits",
                "verbose_name_plural": "Listes de souhaits",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={
                "ordering": ["-added_at"],
                "verbose_name": "Élément de wishlist",
                "verbose_name_plural": "Éléments de wishlist",
            },
        ),
        migrations.RemoveIndex(
            model_name="productpricing",
            name="ecommerce_p_pricing_91525c_idx",
        ),
        migrations.AddField(
            model_name="bulkprice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="cart",
            name="currency",
            field=models.CharField(
                db_index=True,
                default="XOF",
                help_text="Ex: XOF, EUR, USD",
                max_length=5,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optionnel : permet de purger les paniers inactifs.",
                null=True,
                verbose_name="Expire le",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Désactiver un panier sans le supprimer.",
                verbose_name="Actif",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="session_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Pour les paniers invités (si user est vide).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Clé session",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="currency",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optionnel : hérite du panier si vide.",
                max_length=5,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="category",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code stable utilisé pour les SKU. Ex: TECH, PHON, PRINT, SERV.",
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]{3,8}$",
                        "Format invalide. Ex: TECH, PHON, PRINT, SERV (3–8 caractères A-Z/0-9).",
                    )
                ],
                verbose_name="Code catégorie (CATCODE)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Montant",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="Optionnel: hash du PDF pour traçabilité.",
                max_length=64,
                verbose_name="Checksum",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                db_index=True, default="XOF", max_length=10, verbose_name="Devise"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Auto-généré. Ex: INV-20260124-0001",
                max_length=24,
                unique=True,
                verbose_name="Numéro de facture",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Émise le"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("issued", "Émise"),
                    ("void", "Annulée"),
                ],
                db_index=True,
                default="draft",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mise à jour le"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="voided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Annulée le"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Annulée le"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Terminée le"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                db_index=True, default="XOF", max_length=10, verbose_name="Devise"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Montant à soustraire du total.",
                max_digits=12,
                verbose_name="Remise",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payée le"),
        ),
        migrations.AddField(
            model_name="order",
            name="reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Auto-générée. Ex: ORD-20260124-0001",
                max_length=20,
                null=True,
                verbose_name="Référence",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Expédiée le"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Livraison",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Somme des lignes (items).",
                max_digits=12,
                verbose_name="Sous-total",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Taxes",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="currency",
            field=models.CharField(
                db_index=True, default="XOF", max_length=10, verbose_name="Devise"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom produit (snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_sku",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, verbose_name="SKU (snapshot)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="attempt_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Incrémenté à chaque retry / relance.",
                verbose_name="Nombre de tentatives",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Annulée le"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="failed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Échouée le"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="failure_code",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Code d'échec"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="failure_message",
            field=models.TextField(blank=True, verbose_name="Message d'échec"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optionnel: empêche la création de doublons en cas de retry.",
                max_length=80,
                verbose_name="Clé d'idempotence",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="last_webhook_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernier webhook reçu le"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Frais prestataire",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="succeeded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Réussie le"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="track_stock",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Décochez pour services / sur commande (stock illimité).",
                verbose_name="Suivre le stock",
            ),
        ),
        migrations.AddField(
            model_name="productpricing",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Désactiver la tarification sans supprimer.",
                verbose_name="Actif",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Approuvé le"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Désactiver pour masquer sans supprimer.",
                verbose_name="Actif",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modéré par",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="moderation_note",
            field=models.CharField(
                blank=True,
                help_text="Optionnel: raison du refus/suppression.",
                max_length=255,
                verbose_name="Note de modération",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Code stable utilisé pour les SKU. Ex: SOG, DTH, AFR.",
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]{3,8}$",
                        "Format invalide. Ex: SOG, DTH, AFR (3–8 caractères A-Z/0-9).",
                    )
                ],
                verbose_name="Code vendeur (VENDORCODE)",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email de contact"
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Désactiver pour masquer le vendeur sans supprimer ses données.",
                verbose_name="Actif",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone",
            field=models.CharField(blank=True, max_length=40, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="vendor",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Renseigné automatiquement au premier passage à Vérifié.",
                null=True,
                verbose_name="Vérifié le",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="name",
            field=models.CharField(
                default="Wishlist", max_length=120, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mise à jour le"),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Actif"
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/%Y/%m/",
                verbose_name="Fichier PDF",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="ecommerce.order",
                verbose_name="Commande",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Montant total",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="currency",
            field=models.CharField(
                db_index=True, default="XOF", max_length=10, verbose_name="Devise"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Format recommandé : <VENDORCODE>-<CATCODE>-<NNNN> (ex: SOG-TECH-0001).",
                max_length=100,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Approuvé"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                db_index=True,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="is_verified",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Vérifié"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["is_active", "created_at"],
                name="ecommerce_c_is_acti_f1406f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["user", "is_active"], name="ecommerce_c_user_id_9231b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["session_key", "is_active"],
                name="ecommerce_c_session_73ce7b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["expires_at"], name="ecommerce_c_expires_c5a0fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "created_at"], name="ecommerce_c_cart_id_e86aae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["product"], name="ecommerce_c_product_6c0a19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["code"], name="ecommerce_c_code_03eca9_idx"),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["user", "created_at"], name="ecommerce_f_user_id_8e5f1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="favorite",
            index=models.Index(
                fields=["product", "created_at"], name="ecommerce_f_product_d4e109_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="ecommerce_i_invoice_66eb4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "created_at"], name="ecommerce_i_status_ebfed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["order"], name="ecommerce_i_order_i_9a9c03_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["reference"], name="ecommerce_o_referen_19782e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "created_at"], name="ecommerce_o_user_id_cb1717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="ecommerce_o_product_e8ab69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["created_at"], name="ecommerce_o_created_9448b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["order", "created_at"], name="ecommerce_p_order_i_21b106_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider_payment_id"], name="ecommerce_p_provide_c699b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["idempotency_key"], name="ecommerce_p_idempot_312b31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="ecommerce_p_sku_35a263_idx"),
        ),
        migrations.AddIndex(
            model_name="productpricing",
            index=models.Index(
                fields=["pricing_type", "currency", "is_active"],
                name="ecommerce_p_pricing_7988ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "is_active", "is_approved"],
                name="ecommerce_r_product_3147d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["user", "created_at"], name="ecommerce_r_user_id_5bd2b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["rating", "created_at"], name="ecommerce_r_rating_52ad52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["code"], name="ecommerce_v_code_50dfcd_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["slug"], name="ecommerce_v_slug_86ae78_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="ecommerce_v_is_acti_8fce7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(fields=["user"], name="ecommerce_w_user_id_638869_idx"),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(
                fields=["created_at"], name="ecommerce_w_created_1d487e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["wishlist", "is_active", "-added_at"],
                name="ecommerce_w_wishlis_cbf394_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="wishlistitem",
            index=models.Index(
                fields=["product", "is_active"], name="ecommerce_w_product_2951e2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="chk_invoice_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("total_amount__gte", 0)),
                name="chk_order_total_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal_amount__gte", 0)),
                name="chk_order_subtotal_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_amount__gte", 0)),
                name="chk_order_shipping_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="chk_order_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="chk_order_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("reference__isnull", False),
                    models.Q(("reference", ""), _negated=True),
                ),
                fields=("reference",),
                name="uniq_order_reference_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="chk_orderitem_qty_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="chk_orderitem_unitprice_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="chk_payment_amount_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_fee__gte", 0)),
                name="chk_payment_fee_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("provider", "idempotency_key"),
                name="uniq_payment_provider_idempotency_nonempty",
            ),
        ),
        migrations.AddIndex(
            model_name="skusequence",
            index=models.Index(
                fields=["vendor_code", "category_code"],
                name="ecommerce_s_vendor__c7eff4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="skusequence",
            constraint=models.UniqueConstraint(
                fields=("vendor_code", "category_code"),
                name="uniq_sku_sequence_vendor_category",
            ),
        ),
    ]
