# Generated manually (prod-safe) on 2026-01-25
from __future__ import annotations

from django.db import migrations


def forwards(apps, schema_editor):
    """
    Hotfix DB PostgreSQL:
    - crée les tables ecommerce_* manquantes (IF NOT EXISTS)
    - ajoute les colonnes minimales manquantes (ADD COLUMN IF NOT EXISTS)
    - crée quelques index utiles (CREATE INDEX IF NOT EXISTS)

    Objectif: réparer une DB incohérente où des migrations sont marquées appliquées
    mais où certaines relations (tables) n'existent pas.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    sqls: list[str] = []

    # ------------------------------------------------------------------
    # Sequences (si ton 0020 parle d'une sku sequence)
    # ------------------------------------------------------------------
    sqls += [
        "CREATE SEQUENCE IF NOT EXISTS ecommerce_sku_seq;",
    ]

    # ------------------------------------------------------------------
    # Tables à (re)créer si absentes
    # (on crée "id" seulement, puis on ADD COLUMN IF NOT EXISTS)
    # ------------------------------------------------------------------
    sqls += [
        """
        CREATE TABLE IF NOT EXISTS ecommerce_cart (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_cartitem (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_wishlist (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_wishlistitem (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_vendor (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_productimage (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_productpricing (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_bulkprice (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_order (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_orderitem (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_paymenttransaction (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_invoice (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_review (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS ecommerce_favorite (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
        """,
    ]

    # ------------------------------------------------------------------
    # ENSURE columns (tables secondaires)
    # ------------------------------------------------------------------

    # CART
    sqls += [
        "ALTER TABLE ecommerce_cart ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
        "ALTER TABLE ecommerce_cart ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
        "ALTER TABLE ecommerce_cart ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();",
    ]

    # CART ITEM
    sqls += [
        "ALTER TABLE ecommerce_cartitem ADD COLUMN IF NOT EXISTS cart_id bigint NULL;",
        "ALTER TABLE ecommerce_cartitem ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_cartitem ADD COLUMN IF NOT EXISTS quantity integer NOT NULL DEFAULT 1;",
        "ALTER TABLE ecommerce_cartitem ADD COLUMN IF NOT EXISTS unit_price numeric(12,2) NULL;",
        "ALTER TABLE ecommerce_cartitem ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
    ]

    # WISHLIST
    sqls += [
        "ALTER TABLE ecommerce_wishlist ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
        "ALTER TABLE ecommerce_wishlist ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
    ]

    # WISHLIST ITEM
    sqls += [
        "ALTER TABLE ecommerce_wishlistitem ADD COLUMN IF NOT EXISTS wishlist_id bigint NULL;",
        "ALTER TABLE ecommerce_wishlistitem ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_wishlistitem ADD COLUMN IF NOT EXISTS added_at timestamptz NOT NULL DEFAULT now();",
    ]

    # VENDOR
    sqls += [
        "ALTER TABLE ecommerce_vendor ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
        "ALTER TABLE ecommerce_vendor ADD COLUMN IF NOT EXISTS company_name varchar(255) NULL;",
        "ALTER TABLE ecommerce_vendor ADD COLUMN IF NOT EXISTS is_verified boolean NOT NULL DEFAULT false;",
        "ALTER TABLE ecommerce_vendor ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
        "ALTER TABLE ecommerce_vendor ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();",
    ]

    # PRODUCT IMAGE
    sqls += [
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS image varchar(255) NULL;",
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS alt_text varchar(255) NULL;",
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS is_main boolean NOT NULL DEFAULT false;",
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS sort_order integer NOT NULL DEFAULT 0;",
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
        "ALTER TABLE ecommerce_productimage ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();",
    ]

    # PRODUCT PRICING
    sqls += [
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS pricing_type varchar(3) NOT NULL DEFAULT 'B2C';",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS base_price numeric(12,2) NOT NULL DEFAULT 0;",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS promo_price numeric(12,2) NULL;",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS promo_start timestamptz NULL;",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS promo_end timestamptz NULL;",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS currency varchar(5) NOT NULL DEFAULT 'XOF';",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
        "ALTER TABLE ecommerce_productpricing ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();",
    ]

    # BULK PRICE
    sqls += [
        "ALTER TABLE ecommerce_bulkprice ADD COLUMN IF NOT EXISTS pricing_id bigint NULL;",
        "ALTER TABLE ecommerce_bulkprice ADD COLUMN IF NOT EXISTS min_quantity integer NOT NULL DEFAULT 1;",
        "ALTER TABLE ecommerce_bulkprice ADD COLUMN IF NOT EXISTS unit_price numeric(12,2) NOT NULL DEFAULT 0;",
        "ALTER TABLE ecommerce_bulkprice ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
    ]

    # ORDER
    sqls += [
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS uuid varchar(36) NULL;",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS status varchar(30) NOT NULL DEFAULT 'pending';",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS total_amount numeric(12,2) NOT NULL DEFAULT 0;",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS customer_email varchar(254) NULL;",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS customer_phone varchar(30) NULL;",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS customer_name varchar(255) NULL;",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
        "ALTER TABLE ecommerce_order ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();",
    ]

    # ORDER ITEM
    sqls += [
        "ALTER TABLE ecommerce_orderitem ADD COLUMN IF NOT EXISTS order_id bigint NULL;",
        "ALTER TABLE ecommerce_orderitem ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_orderitem ADD COLUMN IF NOT EXISTS quantity integer NOT NULL DEFAULT 1;",
        "ALTER TABLE ecommerce_orderitem ADD COLUMN IF NOT EXISTS unit_price numeric(12,2) NOT NULL DEFAULT 0;",
        "ALTER TABLE ecommerce_orderitem ADD COLUMN IF NOT EXISTS product_sku varchar(100) NULL;",
        "ALTER TABLE ecommerce_orderitem ADD COLUMN IF NOT EXISTS product_name varchar(255) NULL;",
    ]

    # PAYMENT TRANSACTION
    sqls += [
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS uuid varchar(36) NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS order_id bigint NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS provider varchar(30) NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS status varchar(30) NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS amount numeric(12,2) NOT NULL DEFAULT 0;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS currency varchar(5) NOT NULL DEFAULT 'XOF';",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS provider_payment_id varchar(255) NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS payment_url text NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS payload jsonb NULL;",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
        "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();",
    ]

    # INVOICE
    sqls += [
        "ALTER TABLE ecommerce_invoice ADD COLUMN IF NOT EXISTS uuid varchar(36) NULL;",
        "ALTER TABLE ecommerce_invoice ADD COLUMN IF NOT EXISTS order_id bigint NULL;",
        "ALTER TABLE ecommerce_invoice ADD COLUMN IF NOT EXISTS file varchar(255) NULL;",
        "ALTER TABLE ecommerce_invoice ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
    ]

    # REVIEW
    sqls += [
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS rating integer NOT NULL DEFAULT 5;",
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS title varchar(255) NULL;",
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS content text NULL;",
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS is_approved boolean NOT NULL DEFAULT false;",
        "ALTER TABLE ecommerce_review ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
    ]

    # FAVORITE
    sqls += [
        "ALTER TABLE ecommerce_favorite ADD COLUMN IF NOT EXISTS user_id bigint NULL;",
        "ALTER TABLE ecommerce_favorite ADD COLUMN IF NOT EXISTS product_id bigint NULL;",
        "ALTER TABLE ecommerce_favorite ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();",
    ]

    # ------------------------------------------------------------------
    # ENSURE columns (table ecommerce_product, utile si tu as eu vendor_id / is_featured manquants)
    # ------------------------------------------------------------------
    sqls += [
        "ALTER TABLE ecommerce_product ADD COLUMN IF NOT EXISTS vendor_id bigint NULL;",
        "ALTER TABLE ecommerce_product ADD COLUMN IF NOT EXISTS is_featured boolean NOT NULL DEFAULT false;",
        "ALTER TABLE ecommerce_product ADD COLUMN IF NOT EXISTS is_new boolean NOT NULL DEFAULT false;",
        "ALTER TABLE ecommerce_product ADD COLUMN IF NOT EXISTS updated_at timestamptz NULL;",
        "CREATE INDEX IF NOT EXISTS ecommerce_product_vendor_id_idx ON ecommerce_product (vendor_id);",
    ]

    # ------------------------------------------------------------------
    # Indexes (safe)
    # ------------------------------------------------------------------
    sqls += [
        # cart / items
        "CREATE INDEX IF NOT EXISTS ecommerce_cart_user_id_idx ON ecommerce_cart (user_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_cartitem_cart_id_idx ON ecommerce_cartitem (cart_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_cartitem_product_id_idx ON ecommerce_cartitem (product_id);",
        # wishlist
        "CREATE INDEX IF NOT EXISTS ecommerce_wishlist_user_id_idx ON ecommerce_wishlist (user_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_wishlistitem_wishlist_id_idx ON ecommerce_wishlistitem (wishlist_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_wishlistitem_product_id_idx ON ecommerce_wishlistitem (product_id);",
        # vendor
        "CREATE INDEX IF NOT EXISTS ecommerce_vendor_user_id_idx ON ecommerce_vendor (user_id);",
        # productimage/pricing/bulk
        "CREATE INDEX IF NOT EXISTS ecommerce_productimage_product_id_idx ON ecommerce_productimage (product_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_productpricing_product_id_idx ON ecommerce_productpricing (product_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_bulkprice_pricing_id_idx ON ecommerce_bulkprice (pricing_id);",
        # orders
        "CREATE INDEX IF NOT EXISTS ecommerce_order_user_id_idx ON ecommerce_order (user_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_orderitem_order_id_idx ON ecommerce_orderitem (order_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_orderitem_product_id_idx ON ecommerce_orderitem (product_id);",
        # payments/invoice/reviews
        "CREATE INDEX IF NOT EXISTS ecommerce_paymenttransaction_order_id_idx ON ecommerce_paymenttransaction (order_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_invoice_order_id_idx ON ecommerce_invoice (order_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_review_product_id_idx ON ecommerce_review (product_id);",
        # favorite
        "CREATE INDEX IF NOT EXISTS ecommerce_favorite_user_id_idx ON ecommerce_favorite (user_id);",
        "CREATE INDEX IF NOT EXISTS ecommerce_favorite_product_id_idx ON ecommerce_favorite (product_id);",
        "CREATE UNIQUE INDEX IF NOT EXISTS ecommerce_favorite_user_product_uniq ON ecommerce_favorite (user_id, product_id);",
    ]

    for sql in sqls:
        schema_editor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0020_skusequence_alter_cart_options_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
    ]
