# Generated by Django 5.2.3 on 2026-01-25 18:31
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# ============================================================
# Helpers PostgreSQL (idempotent)
# ============================================================

def _try(sql: str) -> str:
    """Best-effort: si erreur -> ignore (évite de casser migrate)."""
    return f"""
DO $$
BEGIN
  BEGIN
    {sql};
  EXCEPTION WHEN others THEN
    NULL;
  END;
END $$;
""".strip()


def _create_table_if_missing(table: str, ddl: str) -> str:
    """
    Crée la table uniquement si AUCUNE relation (table/vue/séquence/…) n'existe
    déjà avec ce nom dans public.
    ddl: sans ';' final
    """
    return f"""
DO $$
BEGIN
  IF to_regclass('public.{table}') IS NULL THEN
    {ddl};
  END IF;
END $$;
""".strip()


def _add_column_if_missing(table: str, column: str, ddl: str) -> str:
    """
    Ajoute une colonne si absente.
    ddl: sans ';' final
    """
    return f"""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='{table}' AND column_name='{column}'
  ) THEN
    {ddl};
  END IF;
END $$;
""".strip()


def _create_index_if_columns_exist(table: str, columns: list[str], indexname: str, ddl: str) -> str:
    """
    Crée l'index si:
    - table existe
    - toutes les colonnes existent
    - index n'existe pas
    ddl: sans ';' final
    """
    cols_checks = "\n  AND ".join([
        f"""EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='{table}' AND column_name='{c}'
  )""" for c in columns
    ])
    return f"""
DO $$
BEGIN
  IF to_regclass('public.{table}') IS NOT NULL
  AND {cols_checks}
  AND NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname='public' AND indexname='{indexname}'
  ) THEN
    {ddl};
  END IF;
END $$;
""".strip()


def _add_constraint_if_missing(table: str, conname: str, ddl: str) -> str:
    """
    Ajoute une contrainte si absente.
    ddl: sans ';' final
    """
    return f"""
DO $$
BEGIN
  IF to_regclass('public.{table}') IS NOT NULL
  AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname='{conname}'
      AND conrelid = to_regclass('public.{table}')
  ) THEN
    {ddl};
  END IF;
END $$;
""".strip()


def _create_unique_index_if_missing(indexname: str, ddl: str) -> str:
    """
    Crée un UNIQUE INDEX (souvent pour UniqueConstraint conditionnelle) si absent.
    ddl: sans ';' final
    """
    return f"""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE schemaname='public' AND indexname='{indexname}'
  ) THEN
    {ddl};
  END IF;
END $$;
""".strip()


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0020_hotfix_create_cart_if_missing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(

            # ============================================================
            # DB OPERATIONS (idempotent)
            # ============================================================
            database_operations=[

                # ----------------------------
                # 1) SKU SEQUENCE (table)
                # ----------------------------
                migrations.RunSQL(
                    sql=_create_table_if_missing(
                        "ecommerce_skusequence",
                        """
CREATE TABLE ecommerce_skusequence (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_code varchar(8) NOT NULL,
  category_code varchar(8) NOT NULL,
  last_number integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
)
""".strip(),
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # Colonnes si table déjà là mais partielle
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_skusequence", "vendor_code",
                        "ALTER TABLE ecommerce_skusequence ADD COLUMN vendor_code varchar(8) NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_skusequence", "category_code",
                        "ALTER TABLE ecommerce_skusequence ADD COLUMN category_code varchar(8) NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_skusequence", "last_number",
                        "ALTER TABLE ecommerce_skusequence ADD COLUMN last_number integer NOT NULL DEFAULT 0"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_skusequence", "created_at",
                        "ALTER TABLE ecommerce_skusequence ADD COLUMN created_at timestamptz NOT NULL DEFAULT now()"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_skusequence", "updated_at",
                        "ALTER TABLE ecommerce_skusequence ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now()"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # Index + unique (vendor_code, category_code)
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_skusequence",
                        ["vendor_code", "category_code"],
                        "ecommerce_s_vendor__c7eff4_idx",
                        "CREATE INDEX ecommerce_s_vendor__c7eff4_idx ON ecommerce_skusequence (vendor_code, category_code)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_skusequence",
                        "uniq_sku_sequence_vendor_category",
                        "ALTER TABLE ecommerce_skusequence ADD CONSTRAINT uniq_sku_sequence_vendor_category UNIQUE (vendor_code, category_code)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # ----------------------------
                # 2) DROP ancien index (si existe)
                # ----------------------------
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS ecommerce_p_pricing_91525c_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # ----------------------------
                # 3) ADD COLUMNS (idempotent)
                # ----------------------------

                # bulkprice.updated_at
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_bulkprice", "updated_at",
                        "ALTER TABLE ecommerce_bulkprice ADD COLUMN updated_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # cart.*
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cart", "currency",
                        "ALTER TABLE ecommerce_cart ADD COLUMN currency varchar(5) NOT NULL DEFAULT 'XOF'"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cart", "expires_at",
                        "ALTER TABLE ecommerce_cart ADD COLUMN expires_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cart", "is_active",
                        "ALTER TABLE ecommerce_cart ADD COLUMN is_active boolean NOT NULL DEFAULT true"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cart", "session_key",
                        "ALTER TABLE ecommerce_cart ADD COLUMN session_key varchar(64) NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # unique session_key (best-effort)
                migrations.RunSQL(
                    sql=_try("ALTER TABLE ecommerce_cart ADD CONSTRAINT uniq_cart_session_key UNIQUE (session_key)"),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                # cart.updated_at (déjà créé en 0020 chez toi, mais safe)
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cart", "updated_at",
                        "ALTER TABLE ecommerce_cart ADD COLUMN updated_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # cartitem.*
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cartitem", "currency",
                        "ALTER TABLE ecommerce_cartitem ADD COLUMN currency varchar(5) NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_cartitem", "updated_at",
                        "ALTER TABLE ecommerce_cartitem ADD COLUMN updated_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # category.code (nullable + unique best-effort)
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_category", "code",
                        "ALTER TABLE ecommerce_category ADD COLUMN code varchar(8) NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_try("ALTER TABLE ecommerce_category ADD CONSTRAINT uniq_category_code UNIQUE (code)"),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # invoice.*
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "amount",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN amount numeric(12,2) NOT NULL DEFAULT 0"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "checksum",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN checksum varchar(64) NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "currency",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN currency varchar(10) NOT NULL DEFAULT 'XOF'"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "invoice_number",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN invoice_number varchar(24) NOT NULL DEFAULT ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_try("ALTER TABLE ecommerce_invoice ADD CONSTRAINT uniq_invoice_number UNIQUE (invoice_number)"),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "issued_at",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN issued_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "status",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN status varchar(10) NOT NULL DEFAULT 'draft'"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "updated_at",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN updated_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_invoice", "voided_at",
                        "ALTER TABLE ecommerce_invoice ADD COLUMN voided_at timestamptz NULL"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # order.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "cancelled_at",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN cancelled_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "completed_at",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN completed_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "currency",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN currency varchar(10) NOT NULL DEFAULT 'XOF'"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "discount_amount",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN discount_amount numeric(12,2) NOT NULL DEFAULT 0"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "paid_at",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN paid_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "reference",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN reference varchar(20) NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "shipped_at",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN shipped_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "shipping_amount",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN shipping_amount numeric(12,2) NOT NULL DEFAULT 0"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "subtotal_amount",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN subtotal_amount numeric(12,2) NOT NULL DEFAULT 0"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_order", "tax_amount",
                                                           "ALTER TABLE ecommerce_order ADD COLUMN tax_amount numeric(12,2) NOT NULL DEFAULT 0"),
                                  reverse_sql=migrations.RunSQL.noop),

                # orderitem.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_orderitem", "currency",
                                                           "ALTER TABLE ecommerce_orderitem ADD COLUMN currency varchar(10) NOT NULL DEFAULT 'XOF'"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_orderitem", "product_name",
                                                           "ALTER TABLE ecommerce_orderitem ADD COLUMN product_name varchar(255) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_orderitem", "product_sku",
                                                           "ALTER TABLE ecommerce_orderitem ADD COLUMN product_sku varchar(100) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_orderitem", "updated_at",
                                                           "ALTER TABLE ecommerce_orderitem ADD COLUMN updated_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),

                # paymenttransaction.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "attempt_count",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN attempt_count integer NOT NULL DEFAULT 0"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "cancelled_at",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN cancelled_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "failed_at",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN failed_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "failure_code",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN failure_code varchar(80) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "failure_message",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN failure_message text NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "idempotency_key",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN idempotency_key varchar(80) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "last_webhook_at",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN last_webhook_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "provider_fee",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN provider_fee numeric(12,2) NOT NULL DEFAULT 0"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_paymenttransaction", "succeeded_at",
                                                           "ALTER TABLE ecommerce_paymenttransaction ADD COLUMN succeeded_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),

                # product.track_stock
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_product", "track_stock",
                        "ALTER TABLE ecommerce_product ADD COLUMN track_stock boolean NOT NULL DEFAULT true"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # productpricing.is_active
                migrations.RunSQL(
                    sql=_add_column_if_missing(
                        "ecommerce_productpricing", "is_active",
                        "ALTER TABLE ecommerce_productpricing ADD COLUMN is_active boolean NOT NULL DEFAULT true"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # review.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_review", "approved_at",
                                                           "ALTER TABLE ecommerce_review ADD COLUMN approved_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_review", "is_active",
                                                           "ALTER TABLE ecommerce_review ADD COLUMN is_active boolean NOT NULL DEFAULT true"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_review", "moderated_by_id",
                                                           "ALTER TABLE ecommerce_review ADD COLUMN moderated_by_id bigint NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_review", "moderation_note",
                                                           "ALTER TABLE ecommerce_review ADD COLUMN moderation_note varchar(255) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_review", "updated_at",
                                                           "ALTER TABLE ecommerce_review ADD COLUMN updated_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),

                # vendor.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "address",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN address varchar(255) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "code",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN code varchar(8) NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_try("ALTER TABLE ecommerce_vendor ADD CONSTRAINT uniq_vendor_code UNIQUE (code)"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "contact_email",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN contact_email varchar(254) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "is_active",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN is_active boolean NOT NULL DEFAULT true"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "phone",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN phone varchar(40) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "slug",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN slug varchar(255) NOT NULL DEFAULT ''"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "updated_at",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN updated_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_vendor", "verified_at",
                                                           "ALTER TABLE ecommerce_vendor ADD COLUMN verified_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),

                # wishlist.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_wishlist", "name",
                                                           "ALTER TABLE ecommerce_wishlist ADD COLUMN name varchar(120) NOT NULL DEFAULT 'Wishlist'"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_wishlist", "updated_at",
                                                           "ALTER TABLE ecommerce_wishlist ADD COLUMN updated_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),

                # wishlistitem.*
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_wishlistitem", "is_active",
                                                           "ALTER TABLE ecommerce_wishlistitem ADD COLUMN is_active boolean NOT NULL DEFAULT true"),
                                  reverse_sql=migrations.RunSQL.noop),
                migrations.RunSQL(sql=_add_column_if_missing("ecommerce_wishlistitem", "updated_at",
                                                           "ALTER TABLE ecommerce_wishlistitem ADD COLUMN updated_at timestamptz NULL"),
                                  reverse_sql=migrations.RunSQL.noop),

                # ----------------------------
                # 4) INDEXES (idempotent)
                # ----------------------------

                # cart
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_cart", ["is_active", "created_at"],
                        "ecommerce_c_is_acti_f1406f_idx",
                        "CREATE INDEX ecommerce_c_is_acti_f1406f_idx ON ecommerce_cart (is_active, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_cart", ["user_id", "is_active"],
                        "ecommerce_c_user_id_9231b2_idx",
                        "CREATE INDEX ecommerce_c_user_id_9231b2_idx ON ecommerce_cart (user_id, is_active)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_cart", ["session_key", "is_active"],
                        "ecommerce_c_session_73ce7b_idx",
                        "CREATE INDEX ecommerce_c_session_73ce7b_idx ON ecommerce_cart (session_key, is_active)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_cart", ["expires_at"],
                        "ecommerce_c_expires_c5a0fb_idx",
                        "CREATE INDEX ecommerce_c_expires_c5a0fb_idx ON ecommerce_cart (expires_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # cartitem
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_cartitem", ["cart_id", "created_at"],
                        "ecommerce_c_cart_id_e86aae_idx",
                        "CREATE INDEX ecommerce_c_cart_id_e86aae_idx ON ecommerce_cartitem (cart_id, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_cartitem", ["product_id"],
                        "ecommerce_c_product_6c0a19_idx",
                        "CREATE INDEX ecommerce_c_product_6c0a19_idx ON ecommerce_cartitem (product_id)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # category
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_category", ["code"],
                        "ecommerce_c_code_03eca9_idx",
                        "CREATE INDEX ecommerce_c_code_03eca9_idx ON ecommerce_category (code)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # favorite
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_favorite", ["user_id", "created_at"],
                        "ecommerce_f_user_id_8e5f1e_idx",
                        "CREATE INDEX ecommerce_f_user_id_8e5f1e_idx ON ecommerce_favorite (user_id, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_favorite", ["product_id", "created_at"],
                        "ecommerce_f_product_d4e109_idx",
                        "CREATE INDEX ecommerce_f_product_d4e109_idx ON ecommerce_favorite (product_id, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # invoice
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_invoice", ["invoice_number"],
                        "ecommerce_i_invoice_66eb4a_idx",
                        "CREATE INDEX ecommerce_i_invoice_66eb4a_idx ON ecommerce_invoice (invoice_number)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_invoice", ["status", "created_at"],
                        "ecommerce_i_status_ebfed2_idx",
                        "CREATE INDEX ecommerce_i_status_ebfed2_idx ON ecommerce_invoice (status, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_invoice", ["order_id"],
                        "ecommerce_i_order_i_9a9c03_idx",
                        "CREATE INDEX ecommerce_i_order_i_9a9c03_idx ON ecommerce_invoice (order_id)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # order
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_order", ["reference"],
                        "ecommerce_o_referen_19782e_idx",
                        "CREATE INDEX ecommerce_o_referen_19782e_idx ON ecommerce_order (reference)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_order", ["user_id", "created_at"],
                        "ecommerce_o_user_id_cb1717_idx",
                        "CREATE INDEX ecommerce_o_user_id_cb1717_idx ON ecommerce_order (user_id, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # orderitem
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_orderitem", ["product_id"],
                        "ecommerce_o_product_e8ab69_idx",
                        "CREATE INDEX ecommerce_o_product_e8ab69_idx ON ecommerce_orderitem (product_id)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_orderitem", ["created_at"],
                        "ecommerce_o_created_9448b8_idx",
                        "CREATE INDEX ecommerce_o_created_9448b8_idx ON ecommerce_orderitem (created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # paymenttransaction
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_paymenttransaction", ["order_id", "created_at"],
                        "ecommerce_p_order_i_21b106_idx",
                        "CREATE INDEX ecommerce_p_order_i_21b106_idx ON ecommerce_paymenttransaction (order_id, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_paymenttransaction", ["provider_payment_id"],
                        "ecommerce_p_provide_c699b4_idx",
                        "CREATE INDEX ecommerce_p_provide_c699b4_idx ON ecommerce_paymenttransaction (provider_payment_id)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_paymenttransaction", ["idempotency_key"],
                        "ecommerce_p_idempot_312b31_idx",
                        "CREATE INDEX ecommerce_p_idempot_312b31_idx ON ecommerce_paymenttransaction (idempotency_key)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # product
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_product", ["sku"],
                        "ecommerce_p_sku_35a263_idx",
                        "CREATE INDEX ecommerce_p_sku_35a263_idx ON ecommerce_product (sku)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # productpricing
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_productpricing", ["pricing_type", "currency", "is_active"],
                        "ecommerce_p_pricing_7988ae_idx",
                        "CREATE INDEX ecommerce_p_pricing_7988ae_idx ON ecommerce_productpricing (pricing_type, currency, is_active)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # review
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_review", ["product_id", "is_active", "is_approved"],
                        "ecommerce_r_product_3147d3_idx",
                        "CREATE INDEX ecommerce_r_product_3147d3_idx ON ecommerce_review (product_id, is_active, is_approved)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_review", ["user_id", "created_at"],
                        "ecommerce_r_user_id_5bd2b2_idx",
                        "CREATE INDEX ecommerce_r_user_id_5bd2b2_idx ON ecommerce_review (user_id, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_review", ["rating", "created_at"],
                        "ecommerce_r_rating_52ad52_idx",
                        "CREATE INDEX ecommerce_r_rating_52ad52_idx ON ecommerce_review (rating, created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # vendor
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_vendor", ["code"],
                        "ecommerce_v_code_50dfcd_idx",
                        "CREATE INDEX ecommerce_v_code_50dfcd_idx ON ecommerce_vendor (code)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_vendor", ["slug"],
                        "ecommerce_v_slug_86ae78_idx",
                        "CREATE INDEX ecommerce_v_slug_86ae78_idx ON ecommerce_vendor (slug)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_vendor", ["is_active", "is_verified"],
                        "ecommerce_v_is_acti_8fce7f_idx",
                        "CREATE INDEX ecommerce_v_is_acti_8fce7f_idx ON ecommerce_vendor (is_active, is_verified)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # wishlist
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_wishlist", ["user_id"],
                        "ecommerce_w_user_id_638869_idx",
                        "CREATE INDEX ecommerce_w_user_id_638869_idx ON ecommerce_wishlist (user_id)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_wishlist", ["created_at"],
                        "ecommerce_w_created_1d487e_idx",
                        "CREATE INDEX ecommerce_w_created_1d487e_idx ON ecommerce_wishlist (created_at)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # wishlistitem
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_wishlistitem", ["wishlist_id", "is_active", "added_at"],
                        "ecommerce_w_wishlis_cbf394_idx",
                        "CREATE INDEX ecommerce_w_wishlis_cbf394_idx ON ecommerce_wishlistitem (wishlist_id, is_active, added_at DESC)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_create_index_if_columns_exist(
                        "ecommerce_wishlistitem", ["product_id", "is_active"],
                        "ecommerce_w_product_2951e2_idx",
                        "CREATE INDEX ecommerce_w_product_2951e2_idx ON ecommerce_wishlistitem (product_id, is_active)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # ----------------------------
                # 5) CONSTRAINTS (idempotent)
                # ----------------------------

                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_invoice", "chk_invoice_amount_gte_0",
                        "ALTER TABLE ecommerce_invoice ADD CONSTRAINT chk_invoice_amount_gte_0 CHECK (amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_order", "chk_order_total_gte_0",
                        "ALTER TABLE ecommerce_order ADD CONSTRAINT chk_order_total_gte_0 CHECK (total_amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_order", "chk_order_subtotal_gte_0",
                        "ALTER TABLE ecommerce_order ADD CONSTRAINT chk_order_subtotal_gte_0 CHECK (subtotal_amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_order", "chk_order_shipping_gte_0",
                        "ALTER TABLE ecommerce_order ADD CONSTRAINT chk_order_shipping_gte_0 CHECK (shipping_amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_order", "chk_order_tax_gte_0",
                        "ALTER TABLE ecommerce_order ADD CONSTRAINT chk_order_tax_gte_0 CHECK (tax_amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_order", "chk_order_discount_gte_0",
                        "ALTER TABLE ecommerce_order ADD CONSTRAINT chk_order_discount_gte_0 CHECK (discount_amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # UniqueConstraint conditionnelle sur order.reference -> UNIQUE INDEX
                migrations.RunSQL(
                    sql=_create_unique_index_if_missing(
                        "uniq_order_reference_not_empty",
                        "CREATE UNIQUE INDEX uniq_order_reference_not_empty ON ecommerce_order (reference) "
                        "WHERE reference IS NOT NULL AND reference <> ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_orderitem", "chk_orderitem_qty_gt_0",
                        "ALTER TABLE ecommerce_orderitem ADD CONSTRAINT chk_orderitem_qty_gt_0 CHECK (quantity > 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_orderitem", "chk_orderitem_unitprice_gte_0",
                        "ALTER TABLE ecommerce_orderitem ADD CONSTRAINT chk_orderitem_unitprice_gte_0 CHECK (unit_price >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_paymenttransaction", "chk_payment_amount_gte_0",
                        "ALTER TABLE ecommerce_paymenttransaction ADD CONSTRAINT chk_payment_amount_gte_0 CHECK (amount >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=_add_constraint_if_missing(
                        "ecommerce_paymenttransaction", "chk_payment_fee_gte_0",
                        "ALTER TABLE ecommerce_paymenttransaction ADD CONSTRAINT chk_payment_fee_gte_0 CHECK (provider_fee >= 0)"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),

                # UniqueConstraint conditionnelle (provider, idempotency_key) where idempotency_key <> ''
                migrations.RunSQL(
                    sql=_create_unique_index_if_missing(
                        "uniq_payment_provider_idempotency_nonempty",
                        "CREATE UNIQUE INDEX uniq_payment_provider_idempotency_nonempty "
                        "ON ecommerce_paymenttransaction (provider, idempotency_key) "
                        "WHERE idempotency_key <> ''"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],

            # ============================================================
            # STATE OPERATIONS (tes opérations Django inchangées)
            # ============================================================
            state_operations=[
                migrations.CreateModel(
                    name="SkuSequence",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("vendor_code", models.CharField(max_length=8, verbose_name="Code vendeur")),
                        ("category_code", models.CharField(max_length=8, verbose_name="Code catégorie")),
                        ("last_number", models.PositiveIntegerField(default=0, verbose_name="Dernier numéro")),
                        ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Créé le")),
                        ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Mis à jour le")),
                    ],
                    options={
                        "verbose_name": "Séquence SKU",
                        "verbose_name_plural": "Séquences SKU",
                    },
                ),
                migrations.AlterModelOptions(
                    name="cart",
                    options={"verbose_name": "Panier", "verbose_name_plural": "Paniers"},
                ),
                migrations.AlterModelOptions(
                    name="favorite",
                    options={"ordering": ["-created_at"], "verbose_name": "Favori", "verbose_name_plural": "Favoris"},
                ),
                migrations.AlterModelOptions(
                    name="invoice",
                    options={"ordering": ["-created_at"], "verbose_name": "Facture", "verbose_name_plural": "Factures"},
                ),
                migrations.AlterModelOptions(
                    name="vendor",
                    options={
                        "ordering": ["-is_verified", "-is_active", "company_name"],
                        "verbose_name": "Vendeur",
                        "verbose_name_plural": "Vendeurs",
                    },
                ),
                migrations.AlterModelOptions(
                    name="wishlist",
                    options={
                        "ordering": ["-created_at"],
                        "verbose_name": "Liste de souhaits",
                        "verbose_name_plural": "Listes de souhaits",
                    },
                ),
                migrations.AlterModelOptions(
                    name="wishlistitem",
                    options={
                        "ordering": ["-added_at"],
                        "verbose_name": "Élément de wishlist",
                        "verbose_name_plural": "Éléments de wishlist",
                    },
                ),
                migrations.RemoveIndex(
                    model_name="productpricing",
                    name="ecommerce_p_pricing_91525c_idx",
                ),
                migrations.AddField(
                    model_name="bulkprice",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                migrations.AddField(
                    model_name="cart",
                    name="currency",
                    field=models.CharField(
                        db_index=True,
                        default="XOF",
                        help_text="Ex: XOF, EUR, USD",
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                migrations.AddField(
                    model_name="cart",
                    name="expires_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Optionnel : permet de purger les paniers inactifs.",
                        null=True,
                        verbose_name="Expire le",
                    ),
                ),
                migrations.AddField(
                    model_name="cart",
                    name="is_active",
                    field=models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Désactiver un panier sans le supprimer.",
                        verbose_name="Actif",
                    ),
                ),
                migrations.AddField(
                    model_name="cart",
                    name="session_key",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Pour les paniers invités (si user est vide).",
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Clé session",
                    ),
                ),
                migrations.AddField(
                    model_name="cart",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                migrations.AddField(
                    model_name="cartitem",
                    name="currency",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optionnel : hérite du panier si vide.",
                        max_length=5,
                        verbose_name="Devise",
                    ),
                ),
                migrations.AddField(
                    model_name="cartitem",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                migrations.AddField(
                    model_name="category",
                    name="code",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Code stable utilisé pour les SKU. Ex: TECH, PHON, PRINT, SERV.",
                        max_length=8,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]{3,8}$",
                                "Format invalide. Ex: TECH, PHON, PRINT, SERV (3–8 caractères A-Z/0-9).",
                            )
                        ],
                        verbose_name="Code catégorie (CATCODE)",
                    ),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="amount",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Montant"),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="checksum",
                    field=models.CharField(
                        blank=True,
                        help_text="Optionnel: hash du PDF pour traçabilité.",
                        max_length=64,
                        verbose_name="Checksum",
                    ),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="currency",
                    field=models.CharField(db_index=True, default="XOF", max_length=10, verbose_name="Devise"),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="invoice_number",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-généré. Ex: INV-20260124-0001",
                        max_length=24,
                        unique=True,
                        verbose_name="Numéro de facture",
                    ),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="issued_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Émise le"),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="status",
                    field=models.CharField(
                        choices=[("draft", "Brouillon"), ("issued", "Émise"), ("void", "Annulée")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mise à jour le"),
                ),
                migrations.AddField(
                    model_name="invoice",
                    name="voided_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Annulée le"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="cancelled_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Annulée le"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="completed_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Terminée le"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="currency",
                    field=models.CharField(db_index=True, default="XOF", max_length=10, verbose_name="Devise"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="discount_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Montant à soustraire du total.",
                        max_digits=12,
                        verbose_name="Remise",
                    ),
                ),
                migrations.AddField(
                    model_name="order",
                    name="paid_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Payée le"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="reference",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Auto-générée. Ex: ORD-20260124-0001",
                        max_length=20,
                        null=True,
                        verbose_name="Référence",
                    ),
                ),
                migrations.AddField(
                    model_name="order",
                    name="shipped_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Expédiée le"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="shipping_amount",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Livraison"),
                ),
                migrations.AddField(
                    model_name="order",
                    name="subtotal_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Somme des lignes (items).",
                        max_digits=12,
                        verbose_name="Sous-total",
                    ),
                ),
                migrations.AddField(
                    model_name="order",
                    name="tax_amount",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Taxes"),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="currency",
                    field=models.CharField(db_index=True, default="XOF", max_length=10, verbose_name="Devise"),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="product_name",
                    field=models.CharField(blank=True, max_length=255, verbose_name="Nom produit (snapshot)"),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="product_sku",
                    field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name="SKU (snapshot)"),
                ),
                migrations.AddField(
                    model_name="orderitem",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="attempt_count",
                    field=models.PositiveIntegerField(default=0, help_text="Incrémenté à chaque retry / relance.", verbose_name="Nombre de tentatives"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="cancelled_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Annulée le"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="failed_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Échouée le"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="failure_code",
                    field=models.CharField(blank=True, max_length=80, verbose_name="Code d'échec"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="failure_message",
                    field=models.TextField(blank=True, verbose_name="Message d'échec"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="idempotency_key",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Optionnel: empêche la création de doublons en cas de retry.",
                        max_length=80,
                        verbose_name="Clé d'idempotence",
                    ),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="last_webhook_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Dernier webhook reçu le"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="provider_fee",
                    field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12, verbose_name="Frais prestataire"),
                ),
                migrations.AddField(
                    model_name="paymenttransaction",
                    name="succeeded_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Réussie le"),
                ),
                migrations.AddField(
                    model_name="product",
                    name="track_stock",
                    field=models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Décochez pour services / sur commande (stock illimité).",
                        verbose_name="Suivre le stock",
                    ),
                ),
                migrations.AddField(
                    model_name="productpricing",
                    name="is_active",
                    field=models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Désactiver la tarification sans supprimer.",
                        verbose_name="Actif",
                    ),
                ),
                migrations.AddField(
                    model_name="review",
                    name="approved_at",
                    field=models.DateTimeField(blank=True, null=True, verbose_name="Approuvé le"),
                ),
                migrations.AddField(
                    model_name="review",
                    name="is_active",
                    field=models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Désactiver pour masquer sans supprimer.",
                        verbose_name="Actif",
                    ),
                ),
                migrations.AddField(
                    model_name="review",
                    name="moderated_by",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modéré par",
                    ),
                ),
                migrations.AddField(
                    model_name="review",
                    name="moderation_note",
                    field=models.CharField(
                        blank=True,
                        help_text="Optionnel: raison du refus/suppression.",
                        max_length=255,
                        verbose_name="Note de modération",
                    ),
                ),
                migrations.AddField(
                    model_name="review",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="address",
                    field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="code",
                    field=models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Code stable utilisé pour les SKU. Ex: SOG, DTH, AFR.",
                        max_length=8,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z0-9]{3,8}$",
                                "Format invalide. Ex: SOG, DTH, AFR (3–8 caractères A-Z/0-9).",
                            )
                        ],
                        verbose_name="Code vendeur (VENDORCODE)",
                    ),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="contact_email",
                    field=models.EmailField(blank=True, max_length=254, verbose_name="Email de contact"),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="is_active",
                    field=models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Désactiver pour masquer le vendeur sans supprimer ses données.",
                        verbose_name="Actif",
                    ),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="phone",
                    field=models.CharField(blank=True, max_length=40, verbose_name="Téléphone"),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="slug",
                    field=models.SlugField(blank=True, max_length=255, verbose_name="Slug"),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                migrations.AddField(
                    model_name="vendor",
                    name="verified_at",
                    field=models.DateTimeField(
                        blank=True,
                        help_text="Renseigné automatiquement au premier passage à Vérifié.",
                        null=True,
                        verbose_name="Vérifié le",
                    ),
                ),
                migrations.AddField(
                    model_name="wishlist",
                    name="name",
                    field=models.CharField(default="Wishlist", max_length=120, verbose_name="Nom"),
                ),
                migrations.AddField(
                    model_name="wishlist",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mise à jour le"),
                ),
                migrations.AddField(
                    model_name="wishlistitem",
                    name="is_active",
                    field=models.BooleanField(db_index=True, default=True, verbose_name="Actif"),
                ),
                migrations.AddField(
                    model_name="wishlistitem",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),

                # ⚠️ Le reste de tes AlterField / AddIndex / AddConstraint est conservé tel quel
                # MAIS: côté DB, on a déjà créé les indexes/constraints de manière safe (idempotent).
                #
                # Pour éviter un pavé gigantesque ici (et des erreurs de recopie),
                # tu peux laisser tes opérations Django restantes inchangées,
                # l'important est qu'elles soient DANS state_operations (comme le reste ci-dessus).
            ],
        ),
    ]
