# Generated by Django 5.2.3 on 2026-01-26 04:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0024_fix_category_legacy_notnull"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="checksum",
            field=models.CharField(
                blank=True,
                help_text="SHA256 du PDF pour traçabilité.",
                max_length=64,
                verbose_name="Checksum",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="provider_event_id",
            field=models.CharField(
                blank=True,
                help_text="ID unique d’événement webhook (utile pour éviter les doublons).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID événement prestataire",
            ),
        ),
        migrations.AddConstraint(
            model_name="bulkprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_quantity__gte", 1)),
                name="chk_bulkprice_minqty_gte_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="bulkprice",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="chk_bulkprice_unitprice_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpricing",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gte", 0)),
                name="chk_pricing_base_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpricing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promo_price__isnull", True),
                    ("promo_price__gte", 0),
                    _connector="OR",
                ),
                name="chk_pricing_promo_gte_0_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpricing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promo_price__isnull", True),
                    ("promo_price__lt", models.F("base_price")),
                    _connector="OR",
                ),
                name="chk_pricing_promo_lt_base_or_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpricing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("promo_start__isnull", True),
                    ("promo_end__isnull", True),
                    ("promo_start__lte", models.F("promo_end")),
                    _connector="OR",
                ),
                name="chk_pricing_promo_start_lte_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="productpricing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("promo_end__isnull", True), ("promo_start__isnull", True)
                    ),
                    ("promo_price__isnull", False),
                    _connector="OR",
                ),
                name="chk_pricing_window_requires_price",
            ),
        ),
    ]
