# Generated by Django 5.2.3 on 2026-01-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0025_alter_invoice_checksum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optionnel. Si renseigné et > prix actuel, affichage prix barré + %.",
                max_digits=12,
                null=True,
                verbose_name="Ancien prix (promo)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sold_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Compteur simple pour l'affichage marketplace. Optionnel.",
                verbose_name="Vendus (compteur)",
            ),
        ),
    ]
