# Generated by Django 5.2.3 on 2026-01-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0026_product_old_price_product_sold_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Adresse"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_country",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Pays"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nom facturation"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="billing_zip",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="Code postal"
            ),
        ),
    ]
