# Generated by Django 5.2.3 on 2026-01-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0027_order_billing_address_order_billing_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_phone",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                verbose_name="Téléphone (facturation)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_note",
            field=models.TextField(blank=True, verbose_name="Note client"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.TextField(blank=True, verbose_name="Adresse (facturation)"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ville"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_country",
            field=models.CharField(blank=True, max_length=120, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                verbose_name="Nom (facturation)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="billing_zip",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Code postal"
            ),
        ),
    ]
