# Generated by Django 5.2.3 on 2026-01-29 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0028_order_billing_phone_order_customer_note_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="chk_order_total_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="chk_order_subtotal_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="chk_order_shipping_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="chk_order_tax_gte_0",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="chk_order_discount_gte_0",
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
