# Generated by Django 5.2.3 on 2026-01-29 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0029_remove_order_chk_order_total_gte_0_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="ecommerce_order",
        ),
    ]
