# Generated by Django 5.2.3 on 2025-12-03 11:41

import django.db.models.deletion
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("about", "À propos"),
                            ("history", "Histoire"),
                            ("vision", "Vision"),
                            ("mission", "Mission"),
                            ("objectives", "Objectifs"),
                            ("values", "Valeurs"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="Photo de l'enfant, affichée sur le formulaire et le reçu",
                        null=True,
                        upload_to="children/",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Date de naissance de l'enfant", null=True
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'école fréquentée par l'enfant",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "school_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CI", "CI"),
                            ("CP", "CP"),
                            ("CE1", "CE1"),
                            ("CE2", "CE2"),
                            ("CM1", "CM1"),
                            ("CM2", "CM2"),
                            ("BEPC", "BEPC"),
                            ("BAC", "BAC"),
                            ("TVET", "TVET"),
                        ],
                        help_text="Classe actuelle de l'enfant",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "annual_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Budget annuel nécessaire pour soutenir l'enfant",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF",
                        help_text="Devise utilisée pour le budget",
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Pays de résidence de l'enfant",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        help_text="Numéro d'identification ou matricule de l'enfant",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfant",
                "verbose_name_plural": "Enfants",
                "ordering": ["translations__name"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HeroBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("background_image", models.ImageField(upload_to="about/hero/")),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Mother",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="mothers/")),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Célibataire"),
                            ("married", "Mariée"),
                            ("widow", "Veuve"),
                            ("separated", "Séparée"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("number_of_children", models.PositiveIntegerField(default=0)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="XOF", max_length=10)),
                (
                    "support_needed",
                    models.CharField(
                        blank=True,
                        help_text="Ex: capital de commerce, formation, logement...",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "capital_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Montant du capital requis pour autonomisation.",
                        max_digits=10,
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "identification_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Organigram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="team/organigram/")),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo du partenaire",
                        null=True,
                        upload_to="partners/",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, help_text="URL du site web du partenaire", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="team/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("board", "Conseil d'administration"),
                            ("employee", "Employé"),
                        ],
                        default="board",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="AboutSubsectionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("content", django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="about/subsections/"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.aboutsubsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "about subsection Translation",
                "db_table": "about_aboutsubsection_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ChildTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom complet de l'enfant", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description ou notes sur l'enfant"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.child",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enfant Translation",
                "db_table": "about_child_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HeroBlockTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.TextField(blank=True)),
                ("button_text", models.CharField(blank=True, max_length=100)),
                ("button_link", models.URLField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.heroblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "hero block Translation",
                "db_table": "about_heroblock_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MotherTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("story", models.TextField(blank=True)),
                ("activity", models.CharField(blank=True, max_length=255)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.mother",
                    ),
                ),
            ],
            options={
                "verbose_name": "mother Translation",
                "db_table": "about_mother_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrganigramTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.organigram",
                    ),
                ),
            ],
            options={
                "verbose_name": "organigram Translation",
                "db_table": "about_organigram_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="PartnerTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nom du partenaire", max_length=150),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description ou informations supplémentaires sur le partenaire",
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire Translation",
                "db_table": "about_partner_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TeamMemberTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="about.teammember",
                    ),
                ),
            ],
            options={
                "verbose_name": "team member Translation",
                "db_table": "about_teammember_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
