# Generated by Django 5.2.3 on 2025-12-31 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
        ("social", "0018_alter_donation_target_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Don",
                "verbose_name_plural": "Dons",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="currency",
            field=models.CharField(
                choices=[("XOF", "XOF"), ("EUR", "EUR"), ("USD", "USD")],
                db_index=True,
                default="XOF",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("wave", "Wave"),
                    ("orange_money", "Orange Money"),
                    ("card", "Carte"),
                    ("bank", "Virement bancaire"),
                    ("cash", "Espèces"),
                    ("other", "Autre"),
                ],
                db_index=True,
                default="",
                max_length=30,
                verbose_name="Méthode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_donations",
                related_query_name="donation_donation",
                to="social.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="receipt_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="donations/receipts/",
                verbose_name="Reçu PDF",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("completed", "Complété"),
                    ("failed", "Échoué"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donation_donations",
                related_query_name="donation_donation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["status"], name="donations_d_status_73ca83_idx"),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["created_at"], name="donations_d_created_26bd74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["currency"], name="donations_d_currenc_3daedf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["payment_method"], name="donations_d_payment_ef61a1_idx"
            ),
        ),
    ]
