# Generated by Django 5.2.3 on 2026-01-08 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Adresse email"),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente de vérification"),
                            ("VERIFIED", "Email vérifié"),
                            ("SENT", "Transmis à l'équipe"),
                            ("REJECTED", "Rejeté"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "verify_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token de vérification",
                    ),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiration du token"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Transmis le"
                    ),
                ),
                (
                    "sender_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP expéditeur"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="User agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Envoyé le"),
                ),
            ],
            options={
                "verbose_name": "Message de contact",
                "verbose_name_plural": "Messages de contact",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="core_contac_status_15488c_idx",
                    ),
                    models.Index(
                        fields=["email", "created_at"],
                        name="core_contac_email_ef108b_idx",
                    ),
                ],
            },
        ),
    ]
