# Generated by Django 5.2.3 on 2026-01-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Transmis à l'équipe"
            ),
        ),
    ]
