# Generated by Django 5.2.3 on 2026-01-31 01:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestations",
            "0003_quote_quoteline_servicefeature_servicepackagefeature_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["-is_featured", "order", "-created_at", "-id"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "ordering": ["order", "-is_featured", "-created_at", "-id"],
                "verbose_name": "Catégorie de service",
                "verbose_name_plural": "Catégories de services",
            },
        ),
        migrations.AlterModelOptions(
            name="servicepackage",
            options={
                "ordering": ["-is_featured", "order", "-created_at", "-id"],
                "verbose_name": "Pack de services",
                "verbose_name_plural": "Packs de services",
            },
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mis en avant"),
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="order",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Ordre d’affichage"
            ),
        ),
        migrations.AddField(
            model_name="servicecategorytranslation",
            name="seo_description",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="SEO description"
            ),
        ),
        migrations.AddField(
            model_name="servicecategorytranslation",
            name="seo_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="SEO title"),
        ),
        migrations.AddField(
            model_name="servicepackage",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publié le"),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to='prestations.servicepackage',
                verbose_name="Pack",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("design", "Design & Communication"),
                    ("cloud", "Hébergement, Cloud & Infrastructure"),
                    ("dev", "Développement Web & Logiciels"),
                    ("automation", "Automatisation & Digitalisation"),
                    ("managed", "Maintenance IT & Infogérance"),
                    ("security", "Sécurité & Sauvegardes"),
                    ("digital", "Service numérique"),
                    ("print", "Impression / Supports"),
                    ("event", "Événementiel"),
                    ("maintenance", "Maintenance / Support"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
                verbose_name="Type de service",
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "EUR"), ("XOF", "XOF"), ("USD", "USD")],
                default="EUR",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="emails_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Comptes e-mail professionnels"
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="included_domain_year",
            field=models.BooleanField(
                default=False, verbose_name="Nom de domaine inclus (1 an)"
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="included_ssl",
            field=models.BooleanField(
                default=True, verbose_name="Certificat SSL inclus"
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="max_pages",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Laisser vide si non applicable / illimité",
                null=True,
                verbose_name="Nombre maximal de pages",
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="support_level",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("priority", "Prioritaire"),
                    ("dedicated", "Dédié"),
                ],
                default="standard",
                max_length=16,
                verbose_name="Niveau de support",
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="tier",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("business", "Business"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                    ("custom", "Sur mesure"),
                ],
                default="starter",
                max_length=16,
                verbose_name="Niveau de pack",
            ),
        ),
        migrations.AlterField(
            model_name="servicepackagefeature",
            name="is_highlight",
            field=models.BooleanField(
                default=False,
                help_text="Feature clé du pack",
                verbose_name="Mettre en évidence",
            ),
        ),
        migrations.AlterField(
            model_name="servicepackagetranslation",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description détaillée"
            ),
        ),
        migrations.AlterField(
            model_name="servicepackagetranslation",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="Phrase courte orientée valeur",
                max_length=220,
                verbose_name="Accroche marketing",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requests",
                to='prestations.service',
                verbose_name="Service",
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Nouvelle"),
                    ("in_progress", "En cours"),
                    ("done", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                db_index=True,
                default="new",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(fields=["slug"], name="services_se_slug_4657d0_idx"),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="services_se_is_acti_e17d79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(fields=["slug"], name="services_se_slug_89aee3_idx"),
        ),
        migrations.AddIndex(
            model_name="servicepackage",
            index=models.Index(fields=["slug"], name="services_se_slug_13d1de_idx"),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["user", "status", "created_at"],
                name="services_se_user_id_caefe1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["service", "created_at"], name="services_se_service_b75a66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["package", "created_at"], name="services_se_package_25d0da_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("service__isnull", False), ("package__isnull", True)),
                    models.Q(("service__isnull", True), ("package__isnull", False)),
                    _connector="OR",
                ),
                name="service_xor_package",
            ),
        ),
    ]
