# economic/prestations/migrations/0005_prestations_rename_state_only.py
# Generated by Django 5.2.3 on 2026-02-02 19:24
#
# ✅ REMPLACE 100% ton 0005 généré (celui que tu as collé) par CE fichier.
# ✅ 0 SQL / 0 création / 0 suppression (no fake)
# ✅ Fix KeyError ('prestations','prestationcategory') en remettant l’ordre correct
#    + en évitant les CreateModel/DeleteModel/RemoveField/AddField qui cassent la DB déjà renommée

from __future__ import annotations

import django.db.models.deletion
import django.utils.timezone
import parler.fields
import parler.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "prestations",
            "0004_alter_service_options_alter_servicecategory_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # =========================
            # DB: RIEN (0 SQL)
            # =========================
            database_operations=[],
            # =========================
            # STATE: on aligne Django
            # =========================
            state_operations=[
                # ------------------------------------------------------------
                # 1) RENOMMER LES MODELS (AVANT toute ref à "prestation*")
                # ------------------------------------------------------------
                migrations.RenameModel(
                    old_name="ServiceCategory",
                    new_name="PrestationCategory",
                ),
                migrations.RenameModel(
                    old_name="Service",
                    new_name="Prestation",
                ),
                migrations.RenameModel(
                    old_name="ServicePackage",
                    new_name="PrestationPackage",
                ),
                migrations.RenameModel(
                    old_name="ServiceRequest",
                    new_name="PrestationRequest",
                ),
                migrations.RenameModel(
                    old_name="ServiceFeature",
                    new_name="PrestationFeature",
                ),
                migrations.RenameModel(
                    old_name="ServicePackageFeature",
                    new_name="PrestationPackageFeature",
                ),

                # Parler translations
                migrations.RenameModel(
                    old_name="ServiceCategoryTranslation",
                    new_name="PrestationCategoryTranslation",
                ),
                migrations.RenameModel(
                    old_name="ServiceTranslation",
                    new_name="PrestationTranslation",
                ),
                migrations.RenameModel(
                    old_name="ServicePackageTranslation",
                    new_name="PrestationPackageTranslation",
                ),

                # ------------------------------------------------------------
                # 2) TABLE NAMES (ta DB est déjà en prestations_*)
                # ------------------------------------------------------------
                migrations.AlterModelTable(
                    name="prestationcategory",
                    table="prestations_prestationcategory",
                ),
                migrations.AlterModelTable(
                    name="prestation",
                    table="prestations_prestation",
                ),
                migrations.AlterModelTable(
                    name="prestationpackage",
                    table="prestations_prestationpackage",
                ),
                migrations.AlterModelTable(
                    name="prestationrequest",
                    table="prestations_prestationrequest",
                ),
                migrations.AlterModelTable(
                    name="prestationfeature",
                    table="prestations_prestationfeature",
                ),
                migrations.AlterModelTable(
                    name="prestationpackagefeature",
                    table="prestations_prestationpackagefeature",
                ),
                migrations.AlterModelTable(
                    name="prestationcategorytranslation",
                    table="prestations_prestationcategory_translation",
                ),
                migrations.AlterModelTable(
                    name="prestationpackagetranslation",
                    table="prestations_prestationpackage_translation",
                ),
                migrations.AlterModelTable(
                    name="prestationtranslation",
                    table="prestations_prestation_translation",
                ),

                # ------------------------------------------------------------
                # 3) RENOMMER LES CHAMPS (aligner sur tes modèles actuels)
                # ------------------------------------------------------------
                # QuoteLine.service -> QuoteLine.prestation
                migrations.RenameField(
                    model_name="quoteline",
                    old_name="service",
                    new_name="prestation",
                ),
                # ServicePackage.services (m2m) -> PrestationPackage.prestations
                migrations.RenameField(
                    model_name="prestationpackage",
                    old_name="services",
                    new_name="prestations",
                ),
                # ServiceFeature.service -> PrestationFeature.prestation
                migrations.RenameField(
                    model_name="prestationfeature",
                    old_name="service",
                    new_name="prestation",
                ),
                # ServiceRequest.service -> PrestationRequest.prestation
                migrations.RenameField(
                    model_name="prestationrequest",
                    old_name="service",
                    new_name="prestation",
                ),

                # ------------------------------------------------------------
                # 4) OPTIONS (comme ton fichier généré, mais après rename)
                # ------------------------------------------------------------
                migrations.AlterModelOptions(
                    name="prestation",
                    options={
                        "verbose_name": "Prestation",
                        "verbose_name_plural": "Prestations",
                        "ordering": ["-is_featured", "order", "-created_at", "-id"],
                    },
                ),
                migrations.AlterModelOptions(
                    name="prestationcategory",
                    options={
                        "ordering": ["order", "-is_featured", "-created_at", "-id"],
                        "verbose_name": "Catégorie de prestations",
                        "verbose_name_plural": "Catégories de prestations",
                    },
                ),
                migrations.AlterModelOptions(
                    name="prestationpackage",
                    options={
                        "verbose_name": "Pack de prestations",
                        "verbose_name_plural": "Packs de prestations",
                        "ordering": ["-is_featured", "order", "-created_at", "-id"],
                    },
                ),
                migrations.AlterModelOptions(
                    name="prestationrequest",
                    options={
                        "verbose_name": "Demande de prestation",
                        "verbose_name_plural": "Demandes de prestations",
                        "ordering": ["-created_at", "-id"],
                    },
                ),
                migrations.AlterModelOptions(
                    name="prestationcategorytranslation",
                    options={
                        "default_permissions": (),
                        "managed": True,
                        "verbose_name": "Catégorie de prestations Translation",
                    },
                ),
                migrations.AlterModelOptions(
                    name="prestationpackagetranslation",
                    options={
                        "default_permissions": (),
                        "managed": True,
                        "verbose_name": "Pack de prestations Translation",
                    },
                ),
                migrations.AlterModelOptions(
                    name="prestationtranslation",
                    options={
                        "default_permissions": (),
                        "managed": True,
                        "verbose_name": "Prestation Translation",
                    },
                ),

                # ------------------------------------------------------------
                # 5) FK targets (state) — IMPORTANT pour éviter les KeyError
                # ------------------------------------------------------------
                migrations.AlterField(
                    model_name="prestation",
                    name="category",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prestations",
                        to="prestations.prestationcategory",
                        verbose_name="Catégorie",
                    ),
                ),
                migrations.AlterField(
                    model_name="quoteline",
                    name="prestation",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="prestations.prestation",
                        verbose_name="Prestation",
                    ),
                ),
                migrations.AlterField(
                    model_name="quoteline",
                    name="package",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quote_lines",
                        to="prestations.prestationpackage",
                        verbose_name="Pack",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationfeature",
                    name="prestation",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="prestations.prestation",
                        verbose_name="Prestation",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationpackagefeature",
                    name="package",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="prestations.prestationpackage",
                        verbose_name="Pack",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationrequest",
                    name="package",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="prestations.prestationpackage",
                        verbose_name="Pack",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationrequest",
                    name="prestation",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="prestations.prestation",
                        verbose_name="Prestation",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationrequest",
                    name="user",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestation_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationtranslation",
                    name="master",
                    field=parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="prestations.prestation",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationcategorytranslation",
                    name="master",
                    field=parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="prestations.prestationcategory",
                    ),
                ),
                migrations.AlterField(
                    model_name="prestationpackagetranslation",
                    name="master",
                    field=parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="prestations.prestationpackage",
                    ),
                ),

                # ------------------------------------------------------------
                # 6) CONSTRAINTS (state)
                # ------------------------------------------------------------
                migrations.RemoveConstraint(
                    model_name="quoteline",
                    name="quote_line_one_ref_or_none",
                ),
                migrations.AddConstraint(
                    model_name="quoteline",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("prestation__isnull", False), ("package__isnull", True)),
                            models.Q(("prestation__isnull", True), ("package__isnull", False)),
                            models.Q(("prestation__isnull", True), ("package__isnull", True)),
                            _connector="OR",
                        ),
                        name="quote_line_one_ref_or_none",
                    ),
                ),
                migrations.RemoveConstraint(
                    model_name="prestationrequest",
                    name="service_xor_package",
                ),
                migrations.AddConstraint(
                    model_name="prestationrequest",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("prestation__isnull", False), ("package__isnull", True)),
                            models.Q(("prestation__isnull", True), ("package__isnull", False)),
                            _connector="OR",
                        ),
                        name="prestation_xor_package",
                    ),
                ),

                # ------------------------------------------------------------
                # 7) INDEX RENAMES (state)
                # ------------------------------------------------------------
                migrations.RenameIndex(
                    model_name="prestationcategory",
                    new_name="prestations_is_acti_5ee4ed_idx",
                    old_name="services_se_is_acti_e17d79_idx",
                ),
                migrations.RenameIndex(
                    model_name="prestationcategory",
                    new_name="prestations_slug_46f05d_idx",
                    old_name="services_se_slug_89aee3_idx",
                ),
                migrations.RenameIndex(
                    model_name="quote",
                    new_name="prestations_status_0c1e3e_idx",
                    old_name="services_qu_status_6e6796_idx",
                ),
                migrations.RenameIndex(
                    model_name="quote",
                    new_name="prestations_currenc_a20688_idx",
                    old_name="services_qu_currenc_610d1b_idx",
                ),
                migrations.RenameIndex(
                    model_name="quoteline",
                    new_name="prestations_quote_i_d4dce5_idx",
                    old_name="services_qu_quote_i_c52dfe_idx",
                ),

                # ------------------------------------------------------------
                # 8) INDEXES (state) — mêmes noms que ton fichier généré
                # ------------------------------------------------------------
                migrations.AddIndex(
                    model_name="prestation",
                    index=models.Index(fields=["slug"], name="prestations_slug_55106b_idx"),
                ),
                migrations.AddIndex(
                    model_name="prestation",
                    index=models.Index(
                        fields=["is_active", "is_featured", "order"],
                        name="prestations_is_acti_557647_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestation",
                    index=models.Index(
                        fields=["prestation_type", "deliverable"],
                        name="prestations_prestat_0b93c4_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationfeature",
                    index=models.Index(
                        fields=["prestation", "order"],
                        name="prestations_prestat_a89909_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationpackage",
                    index=models.Index(fields=["slug"], name="prestations_slug_516896_idx"),
                ),
                migrations.AddIndex(
                    model_name="prestationpackage",
                    index=models.Index(
                        fields=["is_active", "is_featured", "order"],
                        name="prestations_is_acti_fc5571_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationpackage",
                    index=models.Index(
                        fields=["tier", "billing_period", "currency"],
                        name="prestations_tier_a14d28_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationpackagefeature",
                    index=models.Index(
                        fields=["package", "order"],
                        name="prestations_package_084961_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationrequest",
                    index=models.Index(
                        fields=["user", "status", "created_at"],
                        name="prestations_user_id_992f74_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationrequest",
                    index=models.Index(
                        fields=["prestation", "created_at"],
                        name="prestations_prestat_6f9425_idx",
                    ),
                ),
                migrations.AddIndex(
                    model_name="prestationrequest",
                    index=models.Index(
                        fields=["package", "created_at"],
                        name="prestations_package_3e9e73_idx",
                    ),
                ),
            ],
        ),
    ]









# # Generated by Django 5.2.3 on 2026-02-02 19:24

# import django.db.models.deletion
# import django.utils.timezone
# import parler.fields
# import parler.models
# from decimal import Decimal
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         (
#             "prestations",
#             "0004_alter_service_options_alter_servicecategory_options_and_more",
#         ),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name="Prestation",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 (
#                     "slug",
#                     models.SlugField(
#                         blank=True, null=True, unique=True, verbose_name="Slug"
#                     ),
#                 ),
#                 (
#                     "prestation_type",
#                     models.CharField(
#                         choices=[
#                             ("design", "Design & Communication"),
#                             ("cloud", "Hébergement, Cloud & Infrastructure"),
#                             ("dev", "Développement Web & Logiciels"),
#                             ("automation", "Automatisation & Digitalisation"),
#                             ("managed", "Maintenance IT & Infogérance"),
#                             ("security", "Sécurité & Sauvegardes"),
#                             ("digital", "Service numérique"),
#                             ("print", "Impression / Supports"),
#                             ("event", "Événementiel"),
#                             ("maintenance", "Maintenance / Support"),
#                             ("other", "Autre"),
#                         ],
#                         default="other",
#                         max_length=20,
#                         verbose_name="Type de prestation",
#                     ),
#                 ),
#                 (
#                     "deliverable",
#                     models.CharField(
#                         choices=[
#                             ("invitation_card", "Carte d’invitation"),
#                             ("poster", "Affiche"),
#                             ("calendar", "Calendrier"),
#                             ("flyer", "Flyer"),
#                             ("banner", "Bannière"),
#                             ("logo", "Logo"),
#                             ("brochure", "Brochure"),
#                             ("other", "Autre"),
#                         ],
#                         default="other",
#                         max_length=30,
#                         verbose_name="Livrable",
#                     ),
#                 ),
#                 (
#                     "base_price",
#                     models.DecimalField(
#                         decimal_places=2,
#                         default=Decimal("0.00"),
#                         max_digits=12,
#                         verbose_name="Prix de base",
#                     ),
#                 ),
#                 (
#                     "turnaround_days",
#                     models.PositiveIntegerField(
#                         default=3,
#                         help_text="Délai estimé de livraison.",
#                         verbose_name="Délai (jours)",
#                     ),
#                 ),
#                 (
#                     "icon",
#                     models.CharField(
#                         blank=True,
#                         default="fa-solid fa-layer-group",
#                         help_text="Ex: fa-solid fa-cloud, fa-solid fa-shield-halved",
#                         max_length=80,
#                         verbose_name="Icône (FontAwesome)",
#                     ),
#                 ),
#                 (
#                     "order",
#                     models.PositiveIntegerField(
#                         default=100, verbose_name="Ordre d’affichage"
#                     ),
#                 ),
#                 ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
#                 (
#                     "is_featured",
#                     models.BooleanField(default=False, verbose_name="Mis en avant"),
#                 ),
#                 (
#                     "published_at",
#                     models.DateTimeField(
#                         blank=True, null=True, verbose_name="Publié le"
#                     ),
#                 ),
#                 (
#                     "created_at",
#                     models.DateTimeField(
#                         default=django.utils.timezone.now,
#                         editable=False,
#                         verbose_name="Créé le",
#                     ),
#                 ),
#                 (
#                     "updated_at",
#                     models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
#                 ),
#             ],
#             options={
#                 "verbose_name": "Prestation",
#                 "verbose_name_plural": "Prestations",
#                 "ordering": ["-is_featured", "order", "-created_at", "-id"],
#             },
#             bases=(parler.models.TranslatableModelMixin, models.Model),
#         ),
#         migrations.CreateModel(
#             name="PrestationFeature",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("label", models.CharField(max_length=220, verbose_name="Élément")),
#                 (
#                     "order",
#                     models.PositiveIntegerField(default=100, verbose_name="Ordre"),
#                 ),
#             ],
#             options={
#                 "verbose_name": "Prestation — Feature",
#                 "verbose_name_plural": "Prestation — Features",
#                 "ordering": ["order", "id"],
#             },
#         ),
#         migrations.CreateModel(
#             name="PrestationPackage",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 (
#                     "slug",
#                     models.SlugField(
#                         blank=True, null=True, unique=True, verbose_name="Slug"
#                     ),
#                 ),
#                 (
#                     "total_price",
#                     models.DecimalField(
#                         decimal_places=2,
#                         default=Decimal("0.00"),
#                         max_digits=12,
#                         verbose_name="Prix total",
#                     ),
#                 ),
#                 (
#                     "currency",
#                     models.CharField(
#                         choices=[("EUR", "EUR"), ("XOF", "XOF"), ("USD", "USD")],
#                         default="EUR",
#                         max_length=3,
#                         verbose_name="Devise",
#                     ),
#                 ),
#                 (
#                     "billing_period",
#                     models.CharField(
#                         choices=[
#                             ("yearly", "Annuel"),
#                             ("monthly", "Mensuel"),
#                             ("one_time", "Ponctuel"),
#                             ("custom", "Sur devis"),
#                         ],
#                         default="yearly",
#                         max_length=16,
#                         verbose_name="Périodicité",
#                     ),
#                 ),
#                 (
#                     "tier",
#                     models.CharField(
#                         choices=[
#                             ("starter", "Starter"),
#                             ("business", "Business"),
#                             ("premium", "Premium"),
#                             ("enterprise", "Enterprise"),
#                             ("custom", "Sur mesure"),
#                         ],
#                         default="starter",
#                         max_length=16,
#                         verbose_name="Niveau de pack",
#                     ),
#                 ),
#                 (
#                     "support_level",
#                     models.CharField(
#                         choices=[
#                             ("standard", "Standard"),
#                             ("priority", "Prioritaire"),
#                             ("dedicated", "Dédié"),
#                         ],
#                         default="standard",
#                         max_length=16,
#                         verbose_name="Niveau de support",
#                     ),
#                 ),
#                 (
#                     "included_domain_year",
#                     models.BooleanField(
#                         default=False, verbose_name="Nom de domaine inclus (1 an)"
#                     ),
#                 ),
#                 (
#                     "included_ssl",
#                     models.BooleanField(
#                         default=True, verbose_name="Certificat SSL inclus"
#                     ),
#                 ),
#                 (
#                     "emails_count",
#                     models.PositiveIntegerField(
#                         default=0, verbose_name="Comptes e-mail professionnels"
#                     ),
#                 ),
#                 (
#                     "max_pages",
#                     models.PositiveIntegerField(
#                         blank=True,
#                         help_text="Laisser vide si non applicable / illimité",
#                         null=True,
#                         verbose_name="Nombre maximal de pages",
#                     ),
#                 ),
#                 (
#                     "order",
#                     models.PositiveIntegerField(
#                         default=100, verbose_name="Ordre d’affichage"
#                     ),
#                 ),
#                 (
#                     "is_featured",
#                     models.BooleanField(default=False, verbose_name="Mis en avant"),
#                 ),
#                 ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
#                 (
#                     "published_at",
#                     models.DateTimeField(
#                         blank=True, null=True, verbose_name="Publié le"
#                     ),
#                 ),
#                 (
#                     "created_at",
#                     models.DateTimeField(
#                         default=django.utils.timezone.now,
#                         editable=False,
#                         verbose_name="Créé le",
#                     ),
#                 ),
#                 (
#                     "updated_at",
#                     models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
#                 ),
#             ],
#             options={
#                 "verbose_name": "Pack de prestations",
#                 "verbose_name_plural": "Packs de prestations",
#                 "ordering": ["-is_featured", "order", "-created_at", "-id"],
#             },
#             bases=(parler.models.TranslatableModelMixin, models.Model),
#         ),
#         migrations.CreateModel(
#             name="PrestationPackageFeature",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("label", models.CharField(max_length=220, verbose_name="Élément")),
#                 (
#                     "is_highlight",
#                     models.BooleanField(
#                         default=False,
#                         help_text="Feature clé du pack",
#                         verbose_name="Mettre en évidence",
#                     ),
#                 ),
#                 (
#                     "order",
#                     models.PositiveIntegerField(default=100, verbose_name="Ordre"),
#                 ),
#             ],
#             options={
#                 "verbose_name": "Pack — Feature",
#                 "verbose_name_plural": "Pack — Features",
#                 "ordering": ["order", "id"],
#             },
#         ),
#         migrations.CreateModel(
#             name="PrestationRequest",
#             fields=[
#                 (
#                     "id",
#                     models.BigAutoField(
#                         auto_created=True,
#                         primary_key=True,
#                         serialize=False,
#                         verbose_name="ID",
#                     ),
#                 ),
#                 ("subject", models.CharField(max_length=255, verbose_name="Sujet")),
#                 ("message", models.TextField(verbose_name="Besoin / description")),
#                 (
#                     "status",
#                     models.CharField(
#                         choices=[
#                             ("new", "Nouvelle"),
#                             ("in_progress", "En cours"),
#                             ("done", "Terminée"),
#                             ("cancelled", "Annulée"),
#                         ],
#                         db_index=True,
#                         default="new",
#                         max_length=20,
#                         verbose_name="Statut",
#                     ),
#                 ),
#                 (
#                     "created_at",
#                     models.DateTimeField(
#                         default=django.utils.timezone.now,
#                         editable=False,
#                         verbose_name="Créé le",
#                     ),
#                 ),
#                 (
#                     "updated_at",
#                     models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
#                 ),
#             ],
#             options={
#                 "verbose_name": "Demande de prestation",
#                 "verbose_name_plural": "Demandes de prestations",
#                 "ordering": ["-created_at", "-id"],
#             },
#         ),
#         migrations.RenameModel(
#             old_name="ServiceCategoryTranslation",
#             new_name="PrestationCategoryTranslation",
#         ),
#         migrations.RemoveField(
#             model_name="service",
#             name="category",
#         ),
#         migrations.RemoveField(
#             model_name="servicerequest",
#             name="service",
#         ),
#         migrations.RemoveField(
#             model_name="quoteline",
#             name="service",
#         ),
#         migrations.RemoveField(
#             model_name="servicefeature",
#             name="service",
#         ),
#         migrations.RemoveField(
#             model_name="servicepackage",
#             name="services",
#         ),
#         migrations.RemoveField(
#             model_name="servicepackagefeature",
#             name="package",
#         ),
#         migrations.RemoveField(
#             model_name="servicerequest",
#             name="package",
#         ),
#         migrations.RemoveField(
#             model_name="servicerequest",
#             name="user",
#         ),
#         migrations.AlterModelOptions(
#             name="prestationcategory",
#             options={
#                 "ordering": ["order", "-is_featured", "-created_at", "-id"],
#                 "verbose_name": "Catégorie de prestations",
#                 "verbose_name_plural": "Catégories de prestations",
#             },
#         ),
#         migrations.AlterModelOptions(
#             name="prestationcategorytranslation",
#             options={
#                 "default_permissions": (),
#                 "managed": True,
#                 "verbose_name": "Catégorie de prestations Translation",
#             },
#         ),
#         migrations.AlterModelOptions(
#             name="prestationpackagetranslation",
#             options={
#                 "default_permissions": (),
#                 "managed": True,
#                 "verbose_name": "Pack de prestations Translation",
#             },
#         ),
#         migrations.AlterModelOptions(
#             name="prestationtranslation",
#             options={
#                 "default_permissions": (),
#                 "managed": True,
#                 "verbose_name": "Prestation Translation",
#             },
#         ),
#         migrations.RemoveConstraint(
#             model_name="quoteline",
#             name="quote_line_one_ref_or_none",
#         ),
#         migrations.RenameIndex(
#             model_name="prestationcategory",
#             new_name="prestations_is_acti_5ee4ed_idx",
#             old_name="services_se_is_acti_e17d79_idx",
#         ),
#         migrations.RenameIndex(
#             model_name="prestationcategory",
#             new_name="prestations_slug_46f05d_idx",
#             old_name="services_se_slug_89aee3_idx",
#         ),
#         migrations.RenameIndex(
#             model_name="quote",
#             new_name="prestations_status_0c1e3e_idx",
#             old_name="services_qu_status_6e6796_idx",
#         ),
#         migrations.RenameIndex(
#             model_name="quote",
#             new_name="prestations_currenc_a20688_idx",
#             old_name="services_qu_currenc_610d1b_idx",
#         ),
#         migrations.RenameIndex(
#             model_name="quoteline",
#             new_name="prestations_quote_i_d4dce5_idx",
#             old_name="services_qu_quote_i_c52dfe_idx",
#         ),
#         migrations.AlterModelTable(
#             name="prestationcategorytranslation",
#             table="prestations_prestationcategory_translation",
#         ),
#         migrations.AlterModelTable(
#             name="prestationpackagetranslation",
#             table="prestations_prestationpackage_translation",
#         ),
#         migrations.AlterModelTable(
#             name="prestationtranslation",
#             table="prestations_prestation_translation",
#         ),
#         migrations.RenameModel(
#             old_name="ServiceCategory",
#             new_name="PrestationCategory",
#         ),
#         migrations.RenameModel(
#             old_name="ServiceTranslation",
#             new_name="PrestationTranslation",
#         ),
#         migrations.AddField(
#             model_name="prestation",
#             name="category",
#             field=models.ForeignKey(
#                 blank=True,
#                 null=True,
#                 on_delete=django.db.models.deletion.SET_NULL,
#                 related_name="prestations",
#                 to="prestations.prestationcategory",
#                 verbose_name="Catégorie",
#             ),
#         ),
#         migrations.AddField(
#             model_name="quoteline",
#             name="prestation",
#             field=models.ForeignKey(
#                 blank=True,
#                 null=True,
#                 on_delete=django.db.models.deletion.SET_NULL,
#                 related_name="quote_lines",
#                 to="prestations.prestation",
#                 verbose_name="Prestation",
#             ),
#         ),
#         migrations.AlterField(
#             model_name="prestationtranslation",
#             name="master",
#             field=parler.fields.TranslationsForeignKey(
#                 editable=False,
#                 null=True,
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="translations",
#                 to="prestations.prestation",
#             ),
#         ),
#         migrations.AddField(
#             model_name="prestationfeature",
#             name="prestation",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="features",
#                 to="prestations.prestation",
#                 verbose_name="Prestation",
#             ),
#         ),
#         migrations.RenameModel(
#             old_name="ServicePackageTranslation",
#             new_name="PrestationPackageTranslation",
#         ),
#         migrations.AddField(
#             model_name="prestationpackage",
#             name="prestations",
#             field=models.ManyToManyField(
#                 blank=True,
#                 related_name="packages",
#                 to="prestations.prestation",
#                 verbose_name="Prestations incluses",
#             ),
#         ),
#         migrations.AlterField(
#             model_name="prestationpackagetranslation",
#             name="master",
#             field=parler.fields.TranslationsForeignKey(
#                 editable=False,
#                 null=True,
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="translations",
#                 to="prestations.prestationpackage",
#             ),
#         ),
#         migrations.AlterField(
#             model_name="quoteline",
#             name="package",
#             field=models.ForeignKey(
#                 blank=True,
#                 null=True,
#                 on_delete=django.db.models.deletion.SET_NULL,
#                 related_name="quote_lines",
#                 to="prestations.prestationpackage",
#                 verbose_name="Pack",
#             ),
#         ),
#         migrations.AddConstraint(
#             model_name="quoteline",
#             constraint=models.CheckConstraint(
#                 condition=models.Q(
#                     models.Q(("prestation__isnull", False), ("package__isnull", True)),
#                     models.Q(("prestation__isnull", True), ("package__isnull", False)),
#                     models.Q(("prestation__isnull", True), ("package__isnull", True)),
#                     _connector="OR",
#                 ),
#                 name="quote_line_one_ref_or_none",
#             ),
#         ),
#         migrations.AddField(
#             model_name="prestationpackagefeature",
#             name="package",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="features",
#                 to="prestations.prestationpackage",
#                 verbose_name="Pack",
#             ),
#         ),
#         migrations.AddField(
#             model_name="prestationrequest",
#             name="package",
#             field=models.ForeignKey(
#                 blank=True,
#                 null=True,
#                 on_delete=django.db.models.deletion.SET_NULL,
#                 related_name="requests",
#                 to="prestations.prestationpackage",
#                 verbose_name="Pack",
#             ),
#         ),
#         migrations.AddField(
#             model_name="prestationrequest",
#             name="prestation",
#             field=models.ForeignKey(
#                 blank=True,
#                 null=True,
#                 on_delete=django.db.models.deletion.SET_NULL,
#                 related_name="requests",
#                 to="prestations.prestation",
#                 verbose_name="Prestation",
#             ),
#         ),
#         migrations.AddField(
#             model_name="prestationrequest",
#             name="user",
#             field=models.ForeignKey(
#                 on_delete=django.db.models.deletion.CASCADE,
#                 related_name="prestation_requests",
#                 to=settings.AUTH_USER_MODEL,
#                 verbose_name="Utilisateur",
#             ),
#         ),
#         migrations.DeleteModel(
#             name="ServiceFeature",
#         ),
#         migrations.DeleteModel(
#             name="Service",
#         ),
#         migrations.DeleteModel(
#             name="ServicePackageFeature",
#         ),
#         migrations.DeleteModel(
#             name="ServiceRequest",
#         ),
#         migrations.AddIndex(
#             model_name="prestation",
#             index=models.Index(fields=["slug"], name="prestations_slug_55106b_idx"),
#         ),
#         migrations.AddIndex(
#             model_name="prestation",
#             index=models.Index(
#                 fields=["is_active", "is_featured", "order"],
#                 name="prestations_is_acti_557647_idx",
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestation",
#             index=models.Index(
#                 fields=["prestation_type", "deliverable"],
#                 name="prestations_prestat_0b93c4_idx",
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestationfeature",
#             index=models.Index(
#                 fields=["prestation", "order"], name="prestations_prestat_a89909_idx"
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestationpackage",
#             index=models.Index(fields=["slug"], name="prestations_slug_516896_idx"),
#         ),
#         migrations.AddIndex(
#             model_name="prestationpackage",
#             index=models.Index(
#                 fields=["is_active", "is_featured", "order"],
#                 name="prestations_is_acti_fc5571_idx",
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestationpackage",
#             index=models.Index(
#                 fields=["tier", "billing_period", "currency"],
#                 name="prestations_tier_a14d28_idx",
#             ),
#         ),
#         migrations.DeleteModel(
#             name="ServicePackage",
#         ),
#         migrations.AddIndex(
#             model_name="prestationpackagefeature",
#             index=models.Index(
#                 fields=["package", "order"], name="prestations_package_084961_idx"
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestationrequest",
#             index=models.Index(
#                 fields=["user", "status", "created_at"],
#                 name="prestations_user_id_992f74_idx",
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestationrequest",
#             index=models.Index(
#                 fields=["prestation", "created_at"],
#                 name="prestations_prestat_6f9425_idx",
#             ),
#         ),
#         migrations.AddIndex(
#             model_name="prestationrequest",
#             index=models.Index(
#                 fields=["package", "created_at"], name="prestations_package_3e9e73_idx"
#             ),
#         ),
#         migrations.AddConstraint(
#             model_name="prestationrequest",
#             constraint=models.CheckConstraint(
#                 condition=models.Q(
#                     models.Q(("prestation__isnull", False), ("package__isnull", True)),
#                     models.Q(("prestation__isnull", True), ("package__isnull", False)),
#                     _connector="OR",
#                 ),
#                 name="prestation_xor_package",
#             ),
#         ),
#     ]
