# Generated by Django 5.2.3 on 2026-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestations", "0005_prestation_prestationfeature_prestationpackage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="prestationfeature",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Prestation — Feature",
                "verbose_name_plural": "Prestation — Features",
            },
        ),
        migrations.RemoveIndex(
            model_name="prestation",
            name="services_se_is_acti_39af20_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestation",
            name="services_se_service_ec120a_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestation",
            name="services_se_slug_4657d0_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationfeature",
            name="services_se_service_dbccc2_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationpackage",
            name="services_se_is_acti_7960e4_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationpackage",
            name="services_se_tier_6f2667_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationpackage",
            name="services_se_slug_13d1de_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationpackagefeature",
            name="services_se_package_93899d_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationrequest",
            name="services_se_user_id_caefe1_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationrequest",
            name="services_se_service_b75a66_idx",
        ),
        migrations.RemoveIndex(
            model_name="prestationrequest",
            name="services_se_package_25d0da_idx",
        ),
        migrations.RemoveField(
            model_name="prestation",
            name="service_type",
        ),
        migrations.AddField(
            model_name="prestation",
            name="prestation_type",
            field=models.CharField(
                choices=[
                    ("design", "Design & Communication"),
                    ("cloud", "Hébergement, Cloud & Infrastructure"),
                    ("dev", "Développement Web & Logiciels"),
                    ("automation", "Automatisation & Digitalisation"),
                    ("managed", "Maintenance IT & Infogérance"),
                    ("security", "Sécurité & Sauvegardes"),
                    ("digital", "Service numérique"),
                    ("print", "Impression / Supports"),
                    ("event", "Événementiel"),
                    ("maintenance", "Maintenance / Support"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=20,
                verbose_name="Type de prestation",
            ),
        ),
        migrations.AlterField(
            model_name="prestationpackage",
            name="prestations",
            field=models.ManyToManyField(
                blank=True,
                related_name="packages",
                to="prestations.prestation",
                verbose_name="Prestations incluses",
            ),
        ),
        migrations.AlterModelTable(
            name="prestation",
            table=None,
        ),
        migrations.AlterModelTable(
            name="prestationcategory",
            table=None,
        ),
        migrations.AlterModelTable(
            name="prestationfeature",
            table=None,
        ),
        migrations.AlterModelTable(
            name="prestationpackage",
            table=None,
        ),
        migrations.AlterModelTable(
            name="prestationpackagefeature",
            table=None,
        ),
        migrations.AlterModelTable(
            name="prestationrequest",
            table=None,
        ),
    ]
