# Generated by Django 5.2.3 on 2026-02-05 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prestations", "0009_fix_m2m_servicepackage_id_to_prestationpackage_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=220)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("short_description", models.CharField(blank=True, max_length=320)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                ("allow_online_payment", models.BooleanField(default=False)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service (réalisation)"),
                            ("DOWNLOAD", "Digital (fichier à télécharger)"),
                            ("LINK", "Digital (lien privé)"),
                        ],
                        default="SERVICE",
                        max_length=16,
                    ),
                ),
                ("preview_url", models.URLField(blank=True)),
                (
                    "preview_label",
                    models.CharField(blank=True, default="Preview", max_length=64),
                ),
                (
                    "deliverable_file",
                    models.FileField(
                        blank=True, upload_to="prestations/deliverables/%Y/%m/"
                    ),
                ),
                ("deliverable_url", models.URLField(blank=True)),
                ("deliverable_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="prestations.prestationpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "order", "-created_at", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrestationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=220)),
                ("subtitle", models.CharField(blank=True, max_length=255)),
                ("short_description", models.CharField(blank=True, max_length=320)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                ("allow_online_payment", models.BooleanField(default=False)),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service (réalisation)"),
                            ("DOWNLOAD", "Digital (fichier à télécharger)"),
                            ("LINK", "Digital (lien privé)"),
                        ],
                        default="SERVICE",
                        max_length=16,
                    ),
                ),
                ("preview_url", models.URLField(blank=True)),
                (
                    "preview_label",
                    models.CharField(blank=True, default="Preview", max_length=64),
                ),
                (
                    "deliverable_file",
                    models.FileField(
                        blank=True, upload_to="prestations/deliverables/%Y/%m/"
                    ),
                ),
                ("deliverable_url", models.URLField(blank=True)),
                ("deliverable_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="prestations.prestation",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "order", "-created_at", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrestationEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Actif"),
                            ("REVOKED", "Révoqué"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("WAVE", "Wave"),
                            ("ORANGE", "Orange Money"),
                            ("MANUAL", "Manuel"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_ref", models.CharField(blank=True, max_length=128)),
                ("order_reference", models.CharField(blank=True, max_length=64)),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("paid_currency", models.CharField(blank=True, max_length=8)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "download_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("download_limit", models.PositiveSmallIntegerField(default=5)),
                ("download_count", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="prestations.prestationpackage",
                    ),
                ),
                (
                    "package_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="prestations.packageoffer",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="prestations.prestation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestations_entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prestation_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="prestations.prestationplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("summary", models.CharField(blank=True, max_length=320)),
                ("description", models.TextField()),
                ("currency", models.CharField(default="XOF", max_length=8)),
                (
                    "budget_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "budget_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PUBLISHED", "Publié"),
                            ("CLOSED", "Fermé"),
                            ("AWARDED", "Attribué"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Envoyée"),
                            ("SHORTLIST", "Pré-sélectionnée"),
                            ("REJECTED", "Refusée"),
                            ("ACCEPTED", "Acceptée"),
                        ],
                        default="SENT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="prestations.projectcall",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="prestations/projects/%Y/%m/")),
                ("label", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="prestations.projectcall",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="packageoffer",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="prestations_is_acti_6dc034_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="packageoffer",
            index=models.Index(fields=["slug"], name="prestations_slug_fbb52c_idx"),
        ),
        migrations.AddIndex(
            model_name="packageoffer",
            index=models.Index(
                fields=["package", "is_active", "order"],
                name="prestations_package_6125ee_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="packageoffer",
            constraint=models.UniqueConstraint(
                fields=("package", "slug"), name="uniq_package_offer_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationplan",
            index=models.Index(
                fields=["is_active", "is_featured", "order"],
                name="prestations_is_acti_7f7088_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prestationplan",
            index=models.Index(fields=["slug"], name="prestations_slug_eff05a_idx"),
        ),
        migrations.AddIndex(
            model_name="prestationplan",
            index=models.Index(
                fields=["prestation", "is_active", "order"],
                name="prestations_prestat_4cad00_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="prestationplan",
            constraint=models.UniqueConstraint(
                fields=("prestation", "slug"), name="uniq_prestation_plan_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="prestationentitlement",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="prestations_user_id_0a82e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prestationentitlement",
            index=models.Index(
                fields=["download_token"], name="prestations_downloa_ce04df_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prestationentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("package__isnull", True),
                        ("package_offer__isnull", True),
                        ("prestation__isnull", True),
                        ("prestation_plan__isnull", False),
                    ),
                    models.Q(
                        ("package__isnull", True),
                        ("package_offer__isnull", False),
                        ("prestation__isnull", True),
                        ("prestation_plan__isnull", True),
                    ),
                    models.Q(
                        ("package__isnull", True),
                        ("package_offer__isnull", True),
                        ("prestation__isnull", False),
                        ("prestation_plan__isnull", True),
                    ),
                    models.Q(
                        ("package__isnull", False),
                        ("package_offer__isnull", True),
                        ("prestation__isnull", True),
                        ("prestation_plan__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_entitlement_exactly_one_target",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcall",
            index=models.Index(
                fields=["status", "is_public", "-created_at"],
                name="prestations_status_7c25c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectcall",
            index=models.Index(fields=["slug"], name="prestations_slug_0130d5_idx"),
        ),
        migrations.AddIndex(
            model_name="projectbid",
            index=models.Index(
                fields=["project", "status", "-created_at"],
                name="prestations_project_4839a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectbid",
            index=models.Index(
                fields=["bidder", "-created_at"], name="prestations_bidder__cb531b_idx"
            ),
        ),
    ]
