# Generated by Django 5.2.3 on 2025-06-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Nom complet"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="judicial_record",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="judicial_records/",
                verbose_name="Casier judiciaire",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="message",
            field=models.TextField(blank=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts_users.userrole",
                verbose_name="Type d'adhésion",
            ),
        ),
    ]
