# Generated by Django 5.2.3 on 2025-12-22 11:40

import accounts_users.models.economic.company_profile
import accounts_users.models.economic.vendor_profile
import accounts_users.models.users_economic_profile
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0001_initial"),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name="customuser",
        #     options={
        #         "ordering": ["-date_joined"],
        #         "verbose_name": "Utilisateur",
        #         "verbose_name_plural": "Utilisateurs",
        #     },
        # ),
        # migrations.AlterModelOptions(
        #     name="userprofile",
        #     options={
        #         "ordering": ["-created_at"],
        #         "verbose_name": "Profil utilisateur",
        #         "verbose_name_plural": "Profils utilisateur",
        #     },
        # ),
        # migrations.AlterModelOptions(
        #     name="userrole",
        #     options={
        #         "ordering": ["-created_at"],
        #         "verbose_name": "Rôle administratif",
        #         "verbose_name_plural": "Rôles administratifs",
        #     },
        # ),
        # migrations.AlterModelOptions(
        #     name="usersettings",
        #     options={
        #         "ordering": ["-created_at"],
        #         "verbose_name": "Paramètre utilisateur",
        #         "verbose_name_plural": "Paramètres utilisateurs",
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name="userrole",
        #     name="role",
        # ),
        # migrations.RemoveField(
        #     model_name="userrole",
        #     name="user",
        # ),
        # migrations.RemoveField(
        #     model_name="usersettings",
        #     name="notifications_enabled",
        # ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_code",
            field=models.CharField(
                blank=True,
                help_text="Code unique par type d’adhésion (ex: M001, V001, D001)",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Code d'inscription",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="code",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("superuser", "Super-utilisateur"),
                    ("moderator", "Modérateur"),
                ],
                default="admin",
                max_length=50,
                unique=True,
                verbose_name="Code interne",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="label",
            field=models.CharField(
                default="Administrateur", max_length=100, verbose_name="Nom du rôle"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Créé le",
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="dark_mode",
            field=models.BooleanField(default=False, verbose_name="Mode sombre activé"),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="receive_newsletter",
            field=models.BooleanField(
                default=True, verbose_name="Recevoir la newsletter"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="created_at",
        #     field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="date_joined",
        #     field=models.DateTimeField(
        #         default=django.utils.timezone.now, verbose_name="Date d’inscription"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="email",
        #     field=models.EmailField(
        #         max_length=254, unique=True, verbose_name="Adresse e-mail"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="is_active",
        #     field=models.BooleanField(default=False, verbose_name="Actif"),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="is_staff",
        #     field=models.BooleanField(default=False, verbose_name="Membre de l’équipe"),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="is_superuser",
        #     field=models.BooleanField(default=False, verbose_name="Superutilisateur"),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="updated_at",
        #     field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        # ),
        # migrations.AlterField(
        #     model_name="customuser",
        #     name="username",
        #     field=models.CharField(
        #         max_length=150, unique=True, verbose_name="Nom d’utilisateur"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="country",
        #     field=django_countries.fields.CountryField(
        #         blank=True, max_length=2, null=True, verbose_name="Pays"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="created_at",
        #     field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="full_name",
        #     field=models.CharField(
        #         blank=True, max_length=255, null=True, verbose_name="Nom complet"
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="judicial_record",
        #     field=models.FileField(
        #         blank=True,
        #         null=True,
        #         upload_to=accounts_users.models.users_profile.judicial_record_upload_path,
        #         verbose_name="Casier judiciaire",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="message",
        #     field=models.TextField(blank=True, verbose_name="Message"),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="phone",
        #     field=models.CharField(max_length=30, verbose_name="Téléphone"),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="profile_picture",
        #     field=models.ImageField(
        #         blank=True,
        #         null=True,
        #         upload_to=accounts_users.models.users_profile.profile_picture_upload_path,
        #         verbose_name="Photo de profil",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="role",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         to="accounts_users.userrole",
        #         verbose_name="Rôle administratif",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="updated_at",
        #     field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        # ),
        # migrations.AlterField(
        #     model_name="userprofile",
        #     name="user",
        #     field=models.OneToOneField(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="userprofile",
        #         to=settings.AUTH_USER_MODEL,
        #         verbose_name="Utilisateur",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userrole",
        #     name="created_at",
        #     field=models.DateTimeField(
        #         default=django.utils.timezone.now,
        #         editable=False,
        #         verbose_name="Créé le",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="userrole",
        #     name="is_active",
        #     field=models.BooleanField(default=True, verbose_name="Actif"),
        # ),
        # migrations.AlterField(
        #     model_name="userrole",
        #     name="updated_at",
        #     field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        # ),
        # migrations.AlterField(
        #     model_name="usersettings",
        #     name="language",
        #     field=models.CharField(
        #         choices=[("fr", "Français"), ("en", "Anglais")],
        #         default="fr",
        #         max_length=10,
        #         verbose_name="Langue préférée",
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name="usersettings",
        #     name="user",
        #     field=models.OneToOneField(
        #         on_delete=django.db.models.deletion.CASCADE,
        #         related_name="settings",
        #         to=settings.AUTH_USER_MODEL,
        #         verbose_name="Utilisateur",
        #     ),
        # ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Adresse")),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code postal"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to="accounts_users.userprofile",
                        verbose_name="Profil utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
            },
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Nom de la société"),
                ),
                (
                    "owner_name",
                    models.CharField(
                        max_length=255, verbose_name="Nom du représentant légal"
                    ),
                ),
                (
                    "company_address",
                    models.TextField(verbose_name="Adresse de la société"),
                ),
                (
                    "registration_document",
                    models.FileField(
                        upload_to=accounts_users.models.economic.company_profile.company_document_upload,
                        verbose_name="Document d’enregistrement légal",
                    ),
                ),
                (
                    "financial_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=accounts_users.models.economic.company_profile.company_document_upload,
                        verbose_name="Document financier / Good standing",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(
                        default=False, verbose_name="Entreprise vérifiée"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to="accounts_users.userprofile",
                        verbose_name="Profil utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil entreprise",
                "verbose_name_plural": "Profils entreprises",
            },
        ),
        migrations.CreateModel(
            name="MembershipRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code interne"
                    ),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Rôle d’adhésion",
                "verbose_name_plural": "Rôles d’adhésion",
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Upper("code"),
                        name="uniq_membership_role_code_ci",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts_users.membershiprole",
                verbose_name="Type d’adhésion",
            ),
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=255, verbose_name="Nom commercial"),
                ),
                (
                    "ninea",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="NINEA / Identifiant commercial",
                    ),
                ),
                (
                    "business_address",
                    models.TextField(verbose_name="Adresse de l’activité"),
                ),
                (
                    "trade_register_document",
                    models.FileField(
                        upload_to=accounts_users.models.economic.vendor_profile.vendor_document_upload,
                        verbose_name="Registre de commerce / document légal",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Vendeur vérifié"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to="accounts_users.userprofile",
                        verbose_name="Profil utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil vendeur",
                "verbose_name_plural": "Profils vendeurs",
            },
        ),
    ]
