# Generated by Django 5.2.3 on 2025-06-27 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0002_alter_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("SPONSOR", "Sponsor"),
                    ("VOLUNTEER", "Volontaire"),
                    ("MEMBER", "Membre"),
                    ("DONOR", "Donateur"),
                    ("OTHER", "Autre"),
                ],
                default="MEMBER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
