# Generated by Django 5.2.3 on 2025-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_users",
            "0003_alter_customuser_options_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
