# Generated by Django 5.2.3 on 2025-06-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0004_membershiprole_alter_userprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts_users.membershiprole",
                verbose_name="Type d’adhésion",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="judicial_record",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="judicial_records/",
                verbose_name="Casier judiciaire",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Pourquoi souhaitez-vous rejoindre ?",
                verbose_name="Message personnel",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_users",
                to="accounts_users.userrole",
                verbose_name="Rôle (Dashboard)",
            ),
        ),
    ]
