# Generated by Django 5.2.3 on 2025-06-27 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0005_userprofile_membership_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="judicial_record",
            field=models.FileField(
                blank=True, null=True, upload_to="judicial_records/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_profiles",
                to="accounts_users.membershiprole",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_profiles",
                to="accounts_users.userrole",
            ),
        ),
    ]
