# Generated by Django 5.2.3 on 2025-12-22 16:55

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0005_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Code postal"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city_of_residence",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ville de résidence"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_of_birth",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Pays de naissance"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country_of_residence",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Pays de résidence"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="economic_registration_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Code économique",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="economic_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CLIENT", "Client"),
                    ("VENDOR", "Vendeur"),
                    ("B2B", "Entreprise / B2B"),
                ],
                max_length=20,
                null=True,
                verbose_name="Rôle économique",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="function",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Fonction"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Autres noms"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Surnom"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_registration_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Code social",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Code postal"
            ),
        ),
    ]
