# Generated by Django 5.2.3 on 2025-12-23 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_users",
            "0006_companyprofile_postal_code_userprofile_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membership_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d’adhésion"
                    ),
                ),
                (
                    "is_active_member",
                    models.BooleanField(default=False, verbose_name="Membre actif"),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True, verbose_name="Motivation / Engagement social"
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        blank=True,
                        help_text="Ex : week-end, temps partiel, temps plein",
                        max_length=150,
                        verbose_name="Disponibilité",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True,
                        help_text="Compétences utiles pour les actions sociales",
                        verbose_name="Compétences",
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(
                        default=False, verbose_name="Profil social validé"
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de validation"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "membership_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts_users.membershiprole",
                        verbose_name="Type d’adhésion sociale",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profile",
                        to="accounts_users.userprofile",
                        verbose_name="Profil utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil social",
                "verbose_name_plural": "Profils sociaux",
                "ordering": ["-created_at"],
            },
        ),
    ]
