# Generated by Django 5.2.3 on 2025-06-27 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0006_alter_userprofile_judicial_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="membership_profiles",
                to="accounts_users.membershiprole",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dashboard_user_profiles",
                to="accounts_users.userrole",
            ),
        ),
    ]
