# Generated by Django 5.2.3 on 2025-12-24 18:33

import accounts_users.models.social.social_profile
import accounts_users.models.users_economic_profile
import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0007_socialprofile"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du rôle admin"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Rôle administrateur",
                "verbose_name_plural": "Rôles administrateurs",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="UserEconomicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Prénom"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Nom"),
                ),
                (
                    "middle_names",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Autres noms"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=100, verbose_name="Surnom"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lieu de naissance"
                    ),
                ),
                (
                    "country_of_residence",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Pays de résidence"
                    ),
                ),
                (
                    "city_of_residence",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Ville de résidence"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Ad resse")),
                (
                    "country_of_birth",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Pays de naissance"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Profession"
                    ),
                ),
                (
                    "function",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Fonction"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Message")),
                (
                    "economic_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CLIENT", "Client"),
                            ("VENDOR", "Vendeur"),
                            ("B2B", "Entreprise / B2B"),
                        ],
                        max_length=20,
                        verbose_name="Rôle économique",
                    ),
                ),
                (
                    "economic_registration_code",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Généré automatiquement",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Code économique",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=accounts_users.models.users_economic_profile.profile_picture_upload_path,
                        verbose_name="Photo de profil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil économique",
                "verbose_name_plural": "Profils économiques",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="socialprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil social (ONG)",
                "verbose_name_plural": "Profils sociaux (ONG)",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "ordering": ["code"],
                "verbose_name": "Rôle administratif",
                "verbose_name_plural": "Rôles administratifs",
            },
        ),
        migrations.RemoveField(
            model_name="socialprofile",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="address",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="city_of_residence",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country_of_birth",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="country_of_residence",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="economic_registration_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="economic_role",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="function",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="judicial_record",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="place_of_birth",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profession",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="label",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="role",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="city_of_residence",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Ville de résidence"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="country_of_birth",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Pays de naissance"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="country_of_residence",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="Pays de résidence"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="function",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Fonction"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="judicial_record",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts_users.models.social.social_profile.social_judicial_record_upload_path,
                verbose_name="Casier judiciaire (PDF)",
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Autres noms"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Surnom"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=30,
                null=True,
                region=None,
                verbose_name="Téléphone",
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="profession",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts_users.models.social.social_profile.social_profile_picture_upload_path,
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="membershiprole",
            name="code",
            field=models.CharField(
                choices=[
                    ("MEMBER", "Membre"),
                    ("VOLUNTEER", "Volontaire"),
                    ("SPONSOR", "Donateur"),
                    ("INSTITUTION", "Institution"),
                ],
                max_length=20,
                unique=True,
                verbose_name="Code interne",
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="availability",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Disponibilité"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="is_validated",
            field=models.BooleanField(default=False, verbose_name="Validé"),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="skills",
            field=models.TextField(blank=True, verbose_name="Compétences"),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Validé le"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="accounts_users.membershiprole",
                verbose_name="Rôle d’adhésion",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="message",
            field=models.TextField(blank=True, null=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="middle_names",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Autres prénoms"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="social_registration_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Code d’enregistrement social",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("active", "Actif"),
                    ("suspended", "Suspendu"),
                ],
                default="pending",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="code",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("superuser", "Super-utilisateur"),
                    ("moderator", "Modérateur"),
                ],
                default="admin",
                max_length=20,
                unique=True,
                verbose_name="Code interne",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("code"),
                name="uniq_user_role_code_ci",
            ),
        ),
        migrations.AddField(
            model_name="adminrole",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_admin_roles",
                to="auth.permission",
                verbose_name="Permissions",
            ),
        ),
        migrations.AddField(
            model_name="usereconomicprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="economic_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_profile",
                to="accounts_users.usereconomicprofile",
                verbose_name="Profil économique",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_profile",
                to="accounts_users.usereconomicprofile",
                verbose_name="Profil économique",
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_profile",
                to="accounts_users.usereconomicprofile",
                verbose_name="Profil économique",
            ),
        ),
        migrations.AddConstraint(
            model_name="adminrole",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("label"),
                name="uniq_admin_role_label_ci",
            ),
        ),
    ]
