# Generated by Django 5.2.3 on 2025-06-27 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0007_alter_userprofile_membership_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membershiprole",
            options={
                "verbose_name": "Rôle d’adhésion",
                "verbose_name_plural": "Rôles d’adhésion",
            },
        ),
        migrations.AlterField(
            model_name="membershiprole",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_membership",
                to="accounts_users.membershiprole",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_role",
                to="accounts_users.membershiprole",
            ),
        ),
    ]
