# Generated by Django 5.2.3 on 2025-12-24 23:20

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0008_adminrole_usereconomicprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region="FR",
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Téléphone (secondaire)",
            ),
        ),
    ]
