# Generated by Django 5.2.3 on 2025-06-29 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0008_alter_membershiprole_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Validé"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Statut du profil",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=models.CharField(max_length=100, verbose_name="Pays"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Nom complet"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="judicial_record",
            field=models.FileField(
                default="judicial_records/default.pdf",
                upload_to="judicial_records/",
                verbose_name="Casier judiciaire",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_membership",
                to="accounts_users.membershiprole",
                verbose_name="Type d’adhésion",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="message",
            field=models.TextField(blank=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                default="profile_pictures/default.jpg",
                upload_to="profile_pictures/",
                verbose_name="Photo de profil",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprofile_role",
                to="accounts_users.membershiprole",
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière modification"
            ),
        ),
    ]
