# Generated by Django 5.2.3 on 2025-06-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_users",
            "0009_userprofile_status_alter_userprofile_country_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="active"),
        ),
    ]
