# Generated by Django 5.2.3 on 2025-12-27 14:28

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0009_userprofile_phone_number_alter_userprofile_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil utilisateur (social)",
                "verbose_name_plural": "Profils utilisateurs (sociaux)",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="membership_role",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="social_registration_code",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="status",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="message",
            field=models.TextField(blank=True, default="", verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="middle_names",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Autres prénoms"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Surnom"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="",
                help_text="Numéro avec indicatif international. Exemple : +221771234567",
                max_length=128,
                region="SN",
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["phone_number"], name="accounts_us_phone_n_61a1b3_idx"
            ),
        ),
    ]
