# Generated by Django 5.2.3 on 2025-12-28 14:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0011_phoneotp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phoneotp",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Tentatives"
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="is_expired",
            field=models.BooleanField(default=False, verbose_name="Expiré"),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifié le"
            ),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="phone_verified",
            field=models.BooleanField(default=False, verbose_name="Téléphone vérifié"),
        ),
        migrations.AddField(
            model_name="socialprofile",
            name="phone_verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Téléphone vérifié le"
            ),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="code",
            field=models.CharField(max_length=6, verbose_name="Code OTP"),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="expires_at",
            field=models.DateTimeField(verbose_name="Expire le"),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Vérifié"),
        ),
        migrations.AlterField(
            model_name="phoneotp",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True, max_length=128, region=None, verbose_name="Téléphone"
            ),
        ),
        migrations.AddIndex(
            model_name="phoneotp",
            index=models.Index(
                fields=["phone", "code"], name="accounts_us_phone_cb3994_idx"
            ),
        ),
    ]
