# Generated by Django 5.2.3 on 2025-07-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0011_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateur",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="registration_code",
            field=models.CharField(
                blank=True,
                help_text="Code d’identification unique par rôle d’adhésion (ex : M001, D002).",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Code d'inscription",
            ),
        ),
    ]
