# Generated by Django 5.2.3 on 2025-07-02 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0012_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts_users.membershiprole",
                verbose_name="Type d’adhésion",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="registration_code",
            field=models.CharField(
                blank=True,
                help_text="Code unique par type d’adhésion (ex: M001, V001, D001)",
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Code d'inscription",
            ),
        ),
    ]
