# Generated by Django 5.2.3 on 2025-12-31 18:14

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0013_profilevalidation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usereconomicprofile",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="usereconomicprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region="SN",
                verbose_name="Téléphone",
            ),
        ),
    ]
