# Generated by Django 5.2.3 on 2025-07-07 19:40

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts_users",
            "0013_userprofile_status_alter_userprofile_membership_role_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="country",
            field=django_countries.fields.CountryField(
                max_length=2, verbose_name="Pays"
            ),
        ),
    ]
