# Generated by Django 5.2.3 on 2026-01-10 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0014_alter_usereconomicprofile_address_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProfileValidation",
        ),
    ]
