# Generated by Django 5.2.3 on 2026-01-10 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0015_delete_profilevalidation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileValidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("refused", "Refusé"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Décision le"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation",
                        to="accounts_users.userprofile",
                        verbose_name="Profil",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_staff": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_validations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Décision par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation de profil",
                "verbose_name_plural": "Validations de profil",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="accounts_us_status_d2d22b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="accounts_us_created_d42b1a_idx"
                    ),
                ],
            },
        ),
    ]
