# Generated by Django 5.2.3 on 2026-01-11 12:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0016_profilevalidation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(max_length=6, verbose_name="Code OTP")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Vérifié"),
                ),
                (
                    "is_expired",
                    models.BooleanField(default=False, verbose_name="Expiré"),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Tentatives"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vérifié le"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="accounts_us_email_279382_idx"),
                    models.Index(
                        fields=["email", "code"], name="accounts_us_email_8882d1_idx"
                    ),
                ],
            },
        ),
    ]
