# Generated by Django 5.2.3 on 2026-01-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0017_emailotp"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailotp",
            index=models.Index(
                fields=["email", "created_at"], name="accounts_us_email_63b51e_idx"
            ),
        ),
    ]
