# Generated by Django 5.2.3 on 2026-01-18 11:36

import accounts_users.models.registration.document
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0018_emailotp_accounts_us_email_63b51e_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SOCIAL", "Social"),
                            ("ECON_CLIENT", "Client (B2C)"),
                            ("ECON_VENDOR", "Vendeur"),
                            ("ECON_B2B", "Entreprise (B2B)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Refusé"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("track", models.CharField(blank=True, default="", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("ID_FRONT", "Pièce d'identité (recto)"),
                            ("ID_BACK", "Pièce d'identité (verso)"),
                            ("SELFIE", "Selfie / photo"),
                            ("PROOF_ADDRESS", "Justificatif de domicile"),
                            ("BUSINESS_LICENSE", "Autorisation / Registre commerce"),
                            ("TAX_CERTIFICATE", "Attestation fiscale"),
                            ("BANK_RIB", "RIB / Compte bancaire"),
                            ("RCCM", "RCCM / Registre"),
                            ("NINEA", "NINEA / Identifiant"),
                            ("COMPANY_STATUTES", "Statuts"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=accounts_users.models.registration.document._reg_doc_path
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts_users.registrationapplication",
                    ),
                ),
            ],
        ),
    ]
