# Generated by Django 5.2.3 on 2026-01-20 17:22

import accounts_users.models.economic.company_profile
import accounts_users.models.economic.vendor_profile
import accounts_users.models.social.social_profile
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_users", "0019_registrationapplication_registrationdocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilevalidation",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="profilevalidation",
            name="validated_by",
        ),
        migrations.AlterModelOptions(
            name="clientprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil client",
                "verbose_name_plural": "Profils clients",
            },
        ),
        migrations.AlterModelOptions(
            name="companyprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil entreprise",
                "verbose_name_plural": "Profils entreprises",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="vendorprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Profil vendeur",
                "verbose_name_plural": "Profils vendeurs",
            },
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="accepts_marketing",
            field=models.BooleanField(
                default=True, verbose_name="Accepte les offres marketing"
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="preferred_currency",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Devise préférée"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="registration_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RCCM/registre ou identifiant officiel si disponible.",
                max_length=120,
                verbose_name="N° d’enregistrement / RCCM (optionnel)",
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifiée le"
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifiée par",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="economic_registration_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Code d’enregistrement économique",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="economic_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts_users.userrole",
                verbose_name="Rôle économique",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts_users.membershiprole",
                verbose_name="Rôle d’adhésion",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_registration_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Code d’enregistrement social",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("active", "Actif"),
                    ("suspended", "Suspendu"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifié le"
            ),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_staff": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_vendors",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifié par",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Adresse (livraison)",
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Ville (livraison)"
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="postal_code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="company_address",
            field=models.TextField(
                blank=True, default="", verbose_name="Adresse de la société"
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="financial_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts_users.models.economic.company_profile.company_document_upload,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Document financier / Good standing (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="owner_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Nom du représentant légal",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="postal_code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="registration_document",
            field=models.FileField(
                blank=True,
                help_text="PDF recommandé.",
                null=True,
                upload_to=accounts_users.models.economic.company_profile.company_document_upload,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Document d’enregistrement légal (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="address",
            field=models.TextField(blank=True, default="", verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="availability",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Disponibilité"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="city_of_residence",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Ville de résidence",
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Prénom"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="function",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Fonction"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="judicial_record",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts_users.models.social.social_profile.social_judicial_record_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Casier judiciaire (PDF)",
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="membership_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_profiles",
                to="accounts_users.membershiprole",
                verbose_name="Type d’adhésion sociale",
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="middle_names",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Autres noms"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="motivation",
            field=models.TextField(
                blank=True, default="", verbose_name="Motivation / Engagement social"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="nickname",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Surnom"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=128,
                region="SN",
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="place_of_birth",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="profession",
            field=models.CharField(
                blank=True, default="", max_length=150, verbose_name="Profession"
            ),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="skills",
            field=models.TextField(blank=True, default="", verbose_name="Compétences"),
        ),
        migrations.AlterField(
            model_name="socialprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Exemple : +221771234567",
                max_length=128,
                null=True,
                region="SN",
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="business_address",
            field=models.TextField(
                blank=True, default="", verbose_name="Adresse de l’activité"
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="ninea",
            field=models.CharField(
                help_text="Identifiant unique (Sénégal).",
                max_length=100,
                unique=True,
                verbose_name="NINEA / Identifiant commercial",
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="postal_code",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Code postal"
            ),
        ),
        migrations.AlterField(
            model_name="vendorprofile",
            name="trade_register_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts_users.models.economic.vendor_profile.vendor_document_upload,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Registre de commerce / document légal (PDF)",
            ),
        ),
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_42e0a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["verified"], name="accounts_us_verifie_f809fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_f13b2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialprofile",
            index=models.Index(fields=["status"], name="accounts_us_status_493734_idx"),
        ),
        migrations.AddIndex(
            model_name="socialprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_9a8131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialprofile",
            index=models.Index(
                fields=["membership_role"], name="accounts_us_members_4ae098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["status"], name="accounts_us_status_4ba1d3_idx"),
        ),
        migrations.AddIndex(
            model_name="vendorprofile",
            index=models.Index(
                fields=["verified"], name="accounts_us_verifie_2d2d8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendorprofile",
            index=models.Index(
                fields=["created_at"], name="accounts_us_created_9517c5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendorprofile",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("ninea"),
                name="uniq_vendor_ninea_ci",
            ),
        ),
        migrations.DeleteModel(
            name="ProfileValidation",
        ),
    ]
