# Generated by Django 5.2.3 on 2026-01-19 03:17

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formations",
            "0002_alter_course_options_alter_coursetranslation_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="Slug"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
            ],
            options={
                "verbose_name": "Domaine de formation",
                "verbose_name_plural": "Domaines de formation",
                "ordering": ["order", "id"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="certificate",
            options={
                "ordering": ["-issued_at"],
                "verbose_name": "Certificat",
                "verbose_name_plural": "Certificats",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "ordering": ["-enrolled_at"],
                "verbose_name": "Inscription",
                "verbose_name_plural": "Inscriptions",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Leçon",
                "verbose_name_plural": "Leçons",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AddField(
            model_name="certificate",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, unique=True
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="formations/certificates/"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="certificate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="course",
            name="duration_hours",
            field=models.PositiveIntegerField(default=0, verbose_name="Durée (heures)"),
        ),
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Mise en avant"),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="FR", max_length=20, verbose_name="Langue"),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Débutant"),
                    ("intermediate", "Intermédiaire"),
                    ("advanced", "Avancé"),
                ],
                default="beginner",
                max_length=20,
                verbose_name="Niveau",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Laisser vide ou 0 pour gratuit.",
                max_digits=12,
                null=True,
                verbose_name="Prix",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Publié le"),
        ),
        migrations.AddField(
            model_name="course",
            name="type",
            field=models.CharField(
                choices=[
                    ("online", "En ligne"),
                    ("onsite", "Présentiel"),
                    ("blended", "Hybride"),
                ],
                default="online",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="coursetranslation",
            name="short_description",
            field=models.CharField(blank=True, max_length=320, verbose_name="Résumé"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Payé"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="progress_percent",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Progression (%)"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("ACTIVE", "Actif"),
                    ("COMPLETED", "Terminé"),
                    ("CANCELLED", "Annulé"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="formations/lessons/"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="module",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="module",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="course",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="formations.course",
                verbose_name="Formation",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="coursetranslation",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formations_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lessontranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Contenu"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="formations.coursecategory",
                verbose_name="Domaine",
            ),
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_at", models.DateTimeField(verbose_name="Début")),
                ("ends_at", models.DateTimeField(verbose_name="Fin")),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Lieu"),
                ),
                ("meeting_url", models.URLField(blank=True, verbose_name="Lien visio")),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = illimité", verbose_name="Capacité"
                    ),
                ),
                (
                    "is_cancelled",
                    models.BooleanField(default=False, verbose_name="Annulée"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="formations.course",
                        verbose_name="Formation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nom")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description courte"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="formations.coursecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domaine de formation Translation",
                "db_table": "formations_coursecategory_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
