# Generated by Django 5.2.3 on 2026-01-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0003_coursecategory_alter_certificate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Ex : Groupe A, Session janvier, etc.",
                max_length=160,
                verbose_name="Titre (optionnel)",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=40,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="enrollment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificate",
                to="formations.enrollment",
                verbose_name="Inscription",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="formations/certificates/%Y/%m/",
                verbose_name="PDF",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="revoked",
            field=models.BooleanField(default=False, verbose_name="Révoqué"),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordre d’affichage dans les listes",
                verbose_name="Ordre",
            ),
        ),
    ]
