# Generated by Django 5.2.3 on 2026-01-21 22:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0004_coursesession_title_alter_certificate_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseInstructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead", "Principal"),
                            ("assistant", "Assistant"),
                            ("guest", "Invité"),
                        ],
                        default="lead",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d’affichage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Formateur",
                "verbose_name_plural": "Formateurs",
                "ordering": ["course_id", "display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Note (1-5)",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=120, verbose_name="Titre"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Visible"),
                ),
            ],
            options={
                "verbose_name": "Avis",
                "verbose_name_plural": "Avis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Démarré le"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Terminé le"
                    ),
                ),
                (
                    "last_position_seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dernière position (s)"
                    ),
                ),
                (
                    "progress_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Progression (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progression leçon",
                "verbose_name_plural": "Progressions leçon",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="coursesession",
            options={
                "ordering": ["-start_at", "-created_at"],
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["module_id", "order", "id"],
                "verbose_name": "Leçon",
                "verbose_name_plural": "Leçons",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["course_id", "order", "id"],
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="coursesession",
            name="capacity",
        ),
        migrations.RemoveField(
            model_name="coursesession",
            name="ends_at",
        ),
        migrations.RemoveField(
            model_name="coursesession",
            name="is_cancelled",
        ),
        migrations.RemoveField(
            model_name="coursesession",
            name="starts_at",
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoke_reason",
            field=models.CharField(blank=True, max_length=255, verbose_name="Motif"),
        ),
        migrations.AddField(
            model_name="certificate",
            name="revoked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Révoqué le"
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="session",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificates",
                to="formations.coursesession",
                verbose_name="Session",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="formations/courses/covers/%Y/%m/",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="currency",
            field=models.CharField(
                choices=[("XOF", "XOF"), ("EUR", "EUR"), ("USD", "USD")],
                default="XOF",
                max_length=3,
                verbose_name="Devise",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AddField(
            model_name="course",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
        ),
        migrations.AddField(
            model_name="course",
            name="meeting_url",
            field=models.URLField(blank=True, verbose_name="Lien visio (optionnel)"),
        ),
        migrations.AddField(
            model_name="course",
            name="promo_video_url",
            field=models.URLField(blank=True, verbose_name="Vidéo promo (URL)"),
        ),
        migrations.AddField(
            model_name="course",
            name="seat_limit",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Places max"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début"),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="end_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="enroll_close_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Inscriptions fermées le"
            ),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="enroll_open_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Inscriptions ouvertes le"
            ),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="instructors",
            field=models.ManyToManyField(
                blank=True,
                related_name="course_sessions_teaching",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Formateurs (session)",
            ),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="seat_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Vide = illimité.",
                null=True,
                verbose_name="Places max",
            ),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="start_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Début"),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("open", "Ouverte"),
                    ("closed", "Fermée"),
                    ("running", "En cours"),
                    ("ended", "Terminée"),
                    ("cancelled", "Annulée"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="currency",
            field=models.CharField(default="XOF", max_length=3, verbose_name="Devise"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="last_accessed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernier accès"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Payé le"),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_provider",
            field=models.CharField(
                choices=[
                    ("NONE", "Aucun"),
                    ("STRIPE", "Stripe"),
                    ("PAYPAL", "PayPal"),
                    ("WAVE", "Wave"),
                    ("ORANGE_MONEY", "Orange Money"),
                    ("VISA", "Carte (Visa/Mastercard)"),
                    ("MANUAL", "Manuel"),
                ],
                default="NONE",
                max_length=20,
                verbose_name="Moyen de paiement",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Référence paiement"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("UNPAID", "Non payé"),
                    ("PAID", "Payé"),
                    ("FAILED", "Échoué"),
                    ("REFUNDED", "Remboursé"),
                ],
                default="UNPAID",
                max_length=20,
                verbose_name="Statut paiement",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="formations.coursesession",
                verbose_name="Session",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Durée (secondes)",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_preview",
            field=models.BooleanField(
                default=False, verbose_name="Leçon gratuite (preview)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="released_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Disponible à partir de"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Vidéo"),
                    ("article", "Article"),
                    ("quiz", "Quiz"),
                    ("live", "Live"),
                ],
                default="video",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="formations/lessons/videos/%Y/%m/",
                verbose_name="Fichier vidéo",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="course",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificates",
                to="formations.course",
                verbose_name="Formation",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="issued_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Délivré le"),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Laisser vide ou 0 pour gratuit.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Prix",
            ),
        ),
        migrations.AlterField(
            model_name="coursesession",
            name="location",
            field=models.CharField(blank=True, max_length=255, verbose_name="Lieu"),
        ),
        migrations.AlterField(
            model_name="coursesession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Ex: Cohorte Janvier 2026",
                max_length=160,
                verbose_name="Titre de session",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="Terminé (legacy)"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Terminé le"
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="formations.course",
                verbose_name="Formation",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Inscrit le"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="Payé (legacy)"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="progress_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
                verbose_name="Progression (%)",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("ACTIVE", "Actif"),
                    ("COMPLETED", "Terminé"),
                    ("CANCELLED", "Annulé"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="formations_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="formations/lessons/attachments/%Y/%m/",
                verbose_name="Pièce jointe",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, verbose_name="URL vidéo"),
        ),
        migrations.AlterField(
            model_name="module",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="module",
            name="order",
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(fields=["code"], name="formations__code_c64b0a_idx"),
        ),
        migrations.AddIndex(
            model_name="certificate",
            index=models.Index(
                fields=["revoked"], name="formations__revoked_c10c3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_active", "published_at"],
                name="formations__is_acti_189023_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_featured"], name="formations__is_feat_890cfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["type"], name="formations__type_8a42b0_idx"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["level"], name="formations__level_db0610_idx"),
        ),
        migrations.AddIndex(
            model_name="coursesession",
            index=models.Index(
                fields=["course", "status"], name="formations__course__d8c75e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesession",
            index=models.Index(
                fields=["course", "is_active"], name="formations__course__4add27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesession",
            index=models.Index(
                fields=["start_at"], name="formations__start_a_2a182b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesession",
            index=models.Index(fields=["end_at"], name="formations__end_at_8de43a_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["user", "status"], name="formations__user_id_d767aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "status"], name="formations__course__59a2bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "session", "status"],
                name="formations__course__6c63e7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["payment_status"], name="formations__payment_2aeb48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["module", "order"], name="formations__module__624ad7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["is_preview"], name="formations__is_prev_50ebba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["is_active"], name="formations__is_acti_6077ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["course", "order"], name="formations__course__383cfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["is_active"], name="formations__is_acti_ba4964_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "course", "session"),
                name="uniq_enrollment_user_course_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("module", "order"), name="uniq_lesson_order_per_module"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="uniq_module_order_per_course"
            ),
        ),
        migrations.AddField(
            model_name="courseinstructor",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_instructors",
                to="formations.course",
                verbose_name="Formation",
            ),
        ),
        migrations.AddField(
            model_name="courseinstructor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_courses_links",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="formations.course",
                verbose_name="Formation",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to="formations.enrollment",
                verbose_name="Inscription",
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_items",
                to="formations.lesson",
                verbose_name="Leçon",
            ),
        ),
        migrations.AddIndex(
            model_name="courseinstructor",
            index=models.Index(
                fields=["course", "is_active"], name="formations__course__66eb9c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="courseinstructor",
            constraint=models.UniqueConstraint(
                fields=("course", "user"), name="uniq_course_instructor"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursereview",
            constraint=models.UniqueConstraint(
                fields=("course", "user"), name="uniq_review_course_user"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonprogress",
            index=models.Index(
                fields=["enrollment", "lesson"], name="formations__enrollm_528249_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonprogress",
            constraint=models.UniqueConstraint(
                fields=("enrollment", "lesson"),
                name="uniq_lesson_progress_enrollment_lesson",
            ),
        ),
    ]
