# Generated by Django 5.2.3 on 2025-07-07 19:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="date",
            field=models.DateField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 7, 19, 40, 31, 901301, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Date du don",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="donation",
            name="pdf_receipt",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="donations/receipts/",
                verbose_name="Reçu PDF",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant du don"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom du donateur"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email du donateur"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="message",
            field=models.TextField(blank=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Carte (Stripe)"),
                    ("paypal", "PayPal"),
                    ("orange_money", "Orange Money"),
                    ("wave", "Wave"),
                    ("visa", "Visa / Carte bancaire"),
                ],
                default="stripe",
                max_length=20,
                verbose_name="Méthode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="social.project",
                verbose_name="Projet",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Payé"),
                    ("failed", "Échoué"),
                    ("cancelled", "Annulé"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Statut du paiement",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
    ]
