# Generated by Django 5.2.3 on 2025-07-07 23:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_donation_date_donation_pdf_receipt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="don",
            options={
                "ordering": ["-date"],
                "verbose_name": "Don (simple)",
                "verbose_name_plural": "Dons (simples)",
            },
        ),
        migrations.AlterModelOptions(
            name="donation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Don",
                "verbose_name_plural": "Dons",
            },
        ),
        migrations.AlterModelOptions(
            name="engagement",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "Engagement",
                "verbose_name_plural": "Engagements",
            },
        ),
        migrations.AlterModelOptions(
            name="evenement",
            options={
                "ordering": ["-date"],
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
            },
        ),
        migrations.AlterModelOptions(
            name="publication",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
            },
        ),
        migrations.RemoveField(
            model_name="donation",
            name="date",
        ),
        migrations.AddField(
            model_name="engagement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 7, 23, 52, 31, 220140, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evenement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 7, 23, 53, 8, 739941, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Créé le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="evenement",
            name="is_public",
            field=models.BooleanField(
                default=True, verbose_name="Visible publiquement ?"
            ),
        ),
        migrations.AlterField(
            model_name="don",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date du don"),
        ),
        migrations.AlterField(
            model_name="don",
            name="montant",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="don",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="date",
            field=models.DateField(verbose_name="Date de l’engagement"),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif ?"),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="engagement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="publication",
            name="is_public",
            field=models.BooleanField(
                default=True, verbose_name="Visible publiquement ?"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Titre"),
        ),
    ]
