# Generated by Django 5.2.3 on 2025-07-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_don_options_alter_donation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="PDF ou document lié à cette publication (optionnel)",
                null=True,
                upload_to="publications/",
                verbose_name="Document à télécharger (PDF)",
            ),
        ),
    ]
