# Generated by Django 5.2.3 on 2025-07-08 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_documentpurchase"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentpurchase",
            options={
                "verbose_name": "Achat de document",
                "verbose_name_plural": "Achats de documents",
            },
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="Montant payé (FCFA)"
            ),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email de réception"),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="payment_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="ID paiement (Stripe/Paypal/autre)",
            ),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="payment_method",
            field=models.CharField(max_length=20, verbose_name="Méthode de paiement"),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchases",
                to="social.publication",
                verbose_name="Document / Publication",
            ),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="purchased_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Acheté le"),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentpurchase",
            unique_together={("user", "publication")},
        ),
    ]
