# Generated by Django 5.2.3 on 2025-07-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_alter_documentpurchase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpurchase",
            name="copy_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="N° de copie"
            ),
        ),
    ]
