# Generated by Django 5.2.3 on 2025-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0007_documentpurchase_copy_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentpurchase",
            name="has_downloaded",
            field=models.BooleanField(default=False, verbose_name="Déjà téléchargé ?"),
        ),
    ]
