# Generated by Django 5.2.3 on 2025-07-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0008_documentpurchase_has_downloaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentpurchase",
            name="copy_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numéro de copie séquentiel attribué à cet achat.",
                null=True,
                verbose_name="N° de copie",
            ),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="has_downloaded",
            field=models.BooleanField(
                default=False,
                help_text="Empêche le téléchargement multiple. Si True, l'utilisateur doit faire une demande par email pour récupérer à nouveau le document.",
                verbose_name="Déjà téléchargé ?",
            ),
        ),
    ]
