# Generated by Django 5.2.3 on 2025-07-08 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0009_alter_documentpurchase_copy_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="goal",
        ),
        migrations.AddField(
            model_name="donation",
            name="monthly",
            field=models.BooleanField(
                default=False, verbose_name="Don mensuel récurrent ?"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="goal_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=1000000,
                max_digits=12,
                verbose_name="Objectif du projet (FCFA)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom du donateur"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Carte (Stripe)"),
                    ("paypal", "PayPal"),
                    ("orange_money", "Orange Money"),
                    ("wave", "Wave"),
                    ("visa", "Visa / Carte bancaire"),
                ],
                default="stripe",
                max_length=50,
                verbose_name="Méthode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projects/images/",
                verbose_name="Image illustrative",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Projet actif ?"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Nom du projet"),
        ),
    ]
