# Generated by Django 5.2.3 on 2025-07-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0011_alter_documentpurchase_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="goal_amount",
        ),
        migrations.AddField(
            model_name="project",
            name="goal",
            field=models.DecimalField(
                decimal_places=2,
                default=1000000,
                max_digits=12,
                verbose_name="Objectif du projet (FCFA)",
            ),
        ),
    ]
