# Generated by Django 5.2.3 on 2025-08-22 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0012_remove_project_goal_amount_project_goal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Code unique envoyé par email pour autoriser le re-téléchargement.",
                        max_length=64,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Créé le",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expire le"
                    ),
                ),
                (
                    "used",
                    models.BooleanField(default=False, verbose_name="Déjà utilisé ?"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_tokens",
                        to="social.publication",
                        verbose_name="Document",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jeton de téléchargement",
                "verbose_name_plural": "Jetons de téléchargement",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["token"], name="social_down_token_ebdfee_idx"),
                    models.Index(
                        fields=["user", "document"],
                        name="social_down_user_id_0e4c82_idx",
                    ),
                    models.Index(fields=["used"], name="social_down_used_13604f_idx"),
                    models.Index(
                        fields=["expires_at"], name="social_down_expires_26b2f2_idx"
                    ),
                ],
            },
        ),
    ]
