# Generated by Django 5.2.3 on 2025-08-22 18:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0013_downloadtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "copy_number",
                    models.PositiveIntegerField(verbose_name="Numéro de copie"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Acheté le"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PublicationPurchaseCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Compteur d’achats (document)",
                "verbose_name_plural": "Compteurs d’achats (document)",
            },
        ),
        migrations.AlterModelOptions(
            name="documentpurchase",
            options={
                "ordering": ["-purchased_at"],
                "verbose_name": "Achat de document (legacy)",
                "verbose_name_plural": "Achats de documents (legacy)",
            },
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="copy_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Numéro de copie (hérité). Le nouveau système utilise PublicationPurchase.",
                null=True,
                verbose_name="N° de copie",
            ),
        ),
        migrations.AlterField(
            model_name="documentpurchase",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_document_purchases",
                related_query_name="legacy_document_purchase",
                to="social.publication",
                verbose_name="Document / Publication",
            ),
        ),
        migrations.AddIndex(
            model_name="documentpurchase",
            index=models.Index(
                fields=["user", "publication"], name="social_docu_user_id_3d9c43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentpurchase",
            index=models.Index(
                fields=["purchased_at"], name="social_docu_purchas_32107d_idx"
            ),
        ),
        migrations.AddField(
            model_name="publicationpurchase",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchases",
                related_query_name="purchase",
                to="social.publication",
                verbose_name="Document",
            ),
        ),
        migrations.AddField(
            model_name="publicationpurchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publication_purchases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Acheteur",
            ),
        ),
        migrations.AddField(
            model_name="publicationpurchasecounter",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="purchase_counter",
                to="social.publication",
                verbose_name="Document",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="publicationpurchase",
            unique_together={("document", "copy_number")},
        ),
    ]
