# Generated by Django 5.2.3 on 2025-11-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social", "0014_publicationpurchase_publicationpurchasecounter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="target_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
