# Generated by Django 5.2.3 on 2025-11-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0016_alter_donation_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="target_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ID brut de la cible"
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="target_type",
            field=models.CharField(
                blank=True,
                help_text="mother / child / project",
                max_length=50,
                null=True,
                verbose_name="Type de cible (texte)",
            ),
        ),
    ]
