# Generated by Django 5.2.3 on 2025-11-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0017_donation_target_id_donation_target_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="target_type",
            field=models.CharField(
                blank=True,
                help_text="mother / child / project",
                max_length=50,
                null=True,
                verbose_name="Type de cible",
            ),
        ),
    ]
