# Generated by Django 5.2.3 on 2025-12-31 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("social", "0018_alter_donation_target_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="receipt_uid",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant unique public du reçu (généré automatiquement).",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="UID du reçu",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("paid", "Payé"),
                    ("failed", "Échoué"),
                    ("cancelled", "Annulé"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Statut du paiement",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["status", "created_at"], name="social_dona_status_c9bcdd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(fields=["email"], name="social_dona_email_6e5f61_idx"),
        ),
    ]
