# Generated by Django 5.2.3 on 2026-01-21 22:38

import django.db.models.deletion
import social.models.document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0019_donation_receipt_uid_alter_donation_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="PDF, DOCX, image, etc.",
                        upload_to=social.models.document.document_upload_to,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, verbose_name="Visible publiquement ?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=["title"], name="social_docu_title_085fe1_idx"),
                    models.Index(
                        fields=["is_public"], name="social_docu_is_publ_60929e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="social_docu_created_c1b45a_idx"
                    ),
                ],
            },
        ),
    ]
