# Generated by Django 5.2.3 on 2026-02-08 02:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["pole", "company_code", "order", "code", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="accounting__type_a640f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="accounting__pole_f4e99c_idx",
        ),
        migrations.RemoveIndex(
            model_name="account",
            name="accounting__is_acti_3db6bc_idx",
        ),
        migrations.AddField(
            model_name="account",
            name="account_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Numéro de compte (optionnel).",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="company_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Entité (optionnel) : ex ECONOMIC-SN / SOCIAL-RW / ...",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                default="XOF", help_text="Devise de reporting.", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="is_reconcilable",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Reconciliable (banque/caisse) si activé.",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="opening_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="opening_balance_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=1000),
        ),
        migrations.AddField(
            model_name="account",
            name="subtype",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CASH", "Caisse / Cash"),
                    ("BANK", "Compte bancaire"),
                    ("AR", "Clients (Accounts Receivable)"),
                    ("INVENTORY", "Stock / Inventaire"),
                    ("FIXED_ASSET", "Immobilisations"),
                    ("OCA", "Autres actifs courants"),
                    ("AP", "Fournisseurs (Accounts Payable)"),
                    ("TAX_PAYABLE", "Taxes à payer"),
                    ("PAYROLL_LIABILITY", "Charges sociales à payer"),
                    ("OCL", "Autres passifs courants"),
                    ("LTL", "Dettes long terme"),
                    ("PAYROLL", "Charges sociales à payer (legacy)"),
                    ("OWNER_EQUITY", "Capital / Apports"),
                    ("RETAINED_EARNINGS", "Résultats reportés"),
                    ("RETAINED", "Résultats reportés (legacy)"),
                    ("SALES", "Ventes / Chiffre d'affaires"),
                    ("SERVICE_REVENUE", "Prestations / Services"),
                    ("DONATION_INCOME", "Produits de dons"),
                    ("TRAINING_REVENUE", "Produits formations"),
                    ("DIGITAL_GOODS", "Produits numériques"),
                    ("SHIPPING_INCOME", "Produits livraison"),
                    ("DISCOUNT", "Remises / Discounts"),
                    ("COGS_DEFAULT", "COGS"),
                    ("PURCHASES", "Achats"),
                    ("OPERATING_EXPENSE", "Charges d'exploitation"),
                    ("FEES", "Frais (paiement, banque)"),
                    ("MARKETING", "Marketing"),
                    ("SOFTWARE", "Logiciels / SaaS"),
                    ("PAYROLL_EXPENSE", "Salaires"),
                    ("RENT", "Loyer"),
                    ("UTILITIES", "Eau / Électricité / Télécom"),
                    ("TRAVEL", "Déplacements"),
                    ("OTHER_EXP", "Autres charges"),
                ],
                db_index=True,
                default="",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="code",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_system",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="account",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Compte parent (sub-account).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="pole",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ECONOMIC", "Économique"),
                    ("SOCIAL", "Social"),
                    ("INSTITUTION", "Institution"),
                    ("CORE", "Core"),
                ],
                db_index=True,
                default="",
                help_text="Pôle (optionnel) : ECONOMIC / SOCIAL / INSTITUTION / CORE.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Actif"),
                    ("LIABILITY", "Passif"),
                    ("EQUITY", "Capitaux propres"),
                    ("INCOME", "Produit"),
                    ("COGS", "Coût des ventes (COGS)"),
                    ("EXPENSE", "Charge"),
                    ("OTHER_INCOME", "Autres produits"),
                    ("OTHER_EXPENSE", "Autres charges"),
                ],
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["pole", "company_code", "type", "subtype"],
                name="accounting__pole_8f0851_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["pole", "company_code", "is_active"],
                name="accounting__pole_0feace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["pole", "company_code", "is_system"],
                name="accounting__pole_95398f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("pole", "company_code", "code"), name="uniq_account_scope_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("id")), _negated=True),
                name="account_parent_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("account_number", ""), _negated=True),
                fields=("pole", "company_code", "account_number"),
                name="uniq_account_scope_number",
            ),
        ),
    ]
