# Generated by Django 5.2.3 on 2026-02-13 01:37

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_alter_account_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=120, unique=True)),
                ("value", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="journalline",
            options={"ordering": ["entry_id", "line_no", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="journalentry",
            name="uq_accounting_entry_source_kind",
        ),
        migrations.RemoveConstraint(
            model_name="journalline",
            name="ck_line_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="journalline",
            name="ck_line_debit_xor_credit",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="accounting__status_19aa8b_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="accounting__kind_f1c60b_idx",
        ),
        migrations.RemoveIndex(
            model_name="journalentry",
            name="accounting__referen_3e7084_idx",
        ),
        migrations.RemoveField(
            model_name="journalentry",
            name="created_by",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="company_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Entité (optionnel) : ex ECONOMIC-SN / SOCIAL-RW / ...",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="currency",
            field=models.CharField(
                default="XOF", help_text="Devise (reporting/écriture).", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="entry_no",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="fiscal_year",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="pole",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ECONOMIC", "Économique"),
                    ("SOCIAL", "Social"),
                    ("INSTITUTION", "Institution"),
                    ("CORE", "Core"),
                ],
                db_index=True,
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="total_credit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="total_debit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="journalentry",
            name="voided_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="journalline",
            name="customer_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="line_no",
            field=models.PositiveIntegerField(
                db_index=True, default=0, help_text="Numéro de ligne (auto si 0)."
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="journalline",
            name="project_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="journalline",
            name="vendor_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="pole",
            field=models.CharField(
                choices=[
                    ("ECONOMIC", "Économique"),
                    ("SOCIAL", "Social"),
                    ("INSTITUTION", "Institution"),
                    ("CORE", "Core"),
                ],
                db_index=True,
                default="ECONOMIC",
                help_text="Pôle : ECONOMIC / SOCIAL / INSTITUTION / CORE.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Général"),
                    ("PAYMENT", "Paiement"),
                    ("INVOICE", "Facture"),
                    ("BILL", "Facture fournisseur"),
                    ("REFUND", "Remboursement"),
                    ("ADJUSTMENT", "Ajustement"),
                    ("TRANSFER", "Transfert"),
                ],
                db_index=True,
                default="GENERAL",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="posted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("POSTED", "Posté"),
                    ("REVERSED", "Contre-passé"),
                    ("VOID", "Annulé"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["journal", "fiscal_year", "entry_no"],
                name="accounting__journal_ce0dc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["status", "date"], name="accounting__status_755796_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["pole", "company_code", "date"],
                name="accounting__pole_6033e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["kind", "date"], name="accounting__kind_9c90bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="accounting__content_2d5599_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["entry", "line_no"], name="accounting__entry_i_572a52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["customer_ref", "created_at"],
                name="accounting__custome_cb684f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["vendor_ref", "created_at"],
                name="accounting__vendor__55e350_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalline",
            index=models.Index(
                fields=["project_ref", "created_at"],
                name="accounting__project_9106aa_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_no", 0), _negated=True),
                fields=("journal", "fiscal_year", "entry_no"),
                name="uniq_entry_journal_year_no",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("content_type__isnull", False),
                    models.Q(("object_id", ""), _negated=True),
                ),
                fields=("content_type", "object_id", "kind"),
                name="uniq_entry_source_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("reference", ""), _negated=True),
                name="ck_entry_reference_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.UniqueConstraint(
                fields=("entry", "line_no"), name="uniq_journal_line_entry_lineno"
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(("debit__gte", 0), ("credit__gte", 0)),
                name="ck_jl_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="journalline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("debit__gt", 0), ("credit", 0)),
                    models.Q(("credit__gt", 0), ("debit", 0)),
                    _connector="OR",
                ),
                name="ck_jl_debit_xor_credit",
            ),
        ),
    ]
