# Generated by Django 5.2.3 on 2026-02-16 20:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_accountingsequence_alter_journalline_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pole",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=80)),
                ("start_date", models.DateField(db_index=True)),
                ("end_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        db_index=True,
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["pole", "company_code", "status"],
                        name="accounting__pole_f7210d_idx",
                    ),
                    models.Index(
                        fields=["pole", "company_code", "start_date"],
                        name="accounting__pole_01b67a_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="acct_period_end_gte_start",
                    ),
                    models.UniqueConstraint(
                        fields=("pole", "company_code", "start_date", "end_date"),
                        name="uniq_acct_period_scope_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountingAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("POST", "Post entry"),
                            ("UNPOST", "Unpost entry"),
                            ("CLOSE_PERIOD", "Close period"),
                            ("OPEN_PERIOD", "Open period"),
                            ("ADJUST", "Adjust / correction"),
                            ("IMPORT", "Import"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                (
                    "pole",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=16
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("message", models.CharField(blank=True, default="", max_length=240)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["pole", "company_code", "created_at"],
                        name="accounting__pole_b38f59_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="accounting__action_ebd8ed_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="accounting__content_35d9bc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "opening_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "opening_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "movement_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "movement_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "closing_debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "closing_credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_balances",
                        to="accounting.account",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_balances",
                        to="accounting.accountingperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["period_id", "account_id"],
                "indexes": [
                    models.Index(
                        fields=["period", "account"],
                        name="accounting__period__46d0ec_idx",
                    ),
                    models.Index(
                        fields=["account", "created_at"],
                        name="accounting__account_de596a_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "account"),
                        name="uniq_ledger_balance_period_account",
                    )
                ],
            },
        ),
    ]
