# Generated by Django 5.2.3 on 2026-02-16 22:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_accountingperiod_accountingaudit_ledgerbalance"),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_currency", models.CharField(db_index=True, max_length=3)),
                ("quote_currency", models.CharField(db_index=True, max_length=3)),
                ("rate_date", models.DateField(db_index=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("1.00000000"), max_digits=18
                    ),
                ),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-rate_date", "base_currency", "quote_currency"],
                "indexes": [
                    models.Index(
                        fields=["base_currency", "quote_currency", "rate_date"],
                        name="accounting__base_cu_2ae1d7_idx",
                    )
                ],
                "unique_together": {("base_currency", "quote_currency", "rate_date")},
            },
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=7
                    ),
                ),
                ("is_inclusive", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_inclusive"],
                        name="accounting__is_acti_0fa23d_idx",
                    )
                ],
            },
        ),
    ]
