# Generated by Django 5.2.3 on 2026-02-08 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Créé"),
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("FAILED", "Échoué"),
                            ("CANCELED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=16,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("stripe", "Stripe"),
                            ("paypal", "PayPal"),
                            ("wave", "Wave"),
                            ("orange", "Orange Money"),
                            ("visa", "Visa"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "pole",
                    models.CharField(
                        choices=[
                            ("ECONOMIC", "Économique"),
                            ("SOCIAL", "Social"),
                            ("INSTITUTION", "Institution"),
                            ("CORE", "Core"),
                        ],
                        db_index=True,
                        default="ECONOMIC",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                (
                    "return_url",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "cancel_url",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="payments_pa_status_79eeea_idx",
                    ),
                    models.Index(
                        fields=["provider", "provider_ref"],
                        name="payments_pa_provide_1001b2_idx",
                    ),
                    models.Index(
                        fields=["pole", "created_at"],
                        name="payments_pa_pole_fed08f_idx",
                    ),
                ],
            },
        ),
    ]
