# Generated by Django 5.2.3 on 2026-02-08 01:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paymentintent",
            name="payments_pa_status_79eeea_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentintent",
            name="payments_pa_pole_fed08f_idx",
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="checkout_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("DONATION", "Don"),
                    ("PUBLICATION", "Publication"),
                    ("ECOM_ORDER", "Commande e-commerce"),
                    ("FORMATION", "Formation"),
                    ("PRESTATION", "Prestation"),
                    ("PACK", "Pack"),
                    ("OTHER", "Autre"),
                ],
                db_index=True,
                default="OTHER",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="reference",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("wave", "Wave"),
                    ("orange_money", "Orange Money"),
                    ("orange", "Orange (legacy)"),
                    ("visa", "Visa"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="provider_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Créé"),
                    ("PENDING", "En attente"),
                    ("REQUIRES_ACTION", "Action requise"),
                    ("PAID", "Payé"),
                    ("FAILED", "Échoué"),
                    ("CANCELED", "Annulé"),
                    ("REFUNDED", "Remboursé"),
                ],
                db_index=True,
                default="CREATED",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["status", "-created_at"], name="payments_pa_status_6cb6dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["pole", "-created_at"], name="payments_pa_pole_7da2df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["purpose", "-created_at"], name="payments_pa_purpose_c2ad64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["reference"], name="payments_pa_referen_544edd_idx"
            ),
        ),
    ]
