# Generated by Django 5.2.3 on 2026-02-08 02:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        (
            "payments",
            "0002_remove_paymentintent_payments_pa_status_79eeea_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paymentintent",
            name="payments_pa_status_6cb6dd_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentintent",
            name="payments_pa_pole_7da2df_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymentintent",
            name="payments_pa_purpose_c2ad64_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="pay_provider_ref_idx",
            old_name="payments_pa_provide_1001b2_idx",
        ),
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="pay_reference_idx",
            old_name="payments_pa_referen_544edd_idx",
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["status", "created_at"], name="pay_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["pole", "created_at"], name="pay_pole_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(
                fields=["purpose", "created_at"], name="pay_purpose_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="pay_amount_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentintent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_ref", ""), _negated=True),
                fields=("provider", "provider_ref"),
                name="pay_unique_provider_ref_not_empty",
            ),
        ),
    ]
