# Generated by Django 5.2.3 on 2026-01-06 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "facility_type",
                    models.CharField(
                        choices=[
                            ("SCHOOL", "École"),
                            ("HEALTH", "Santé / Centre médical"),
                            ("YOUTH", "Jeunesse / Récréation"),
                            ("OTHER", "Autre"),
                        ],
                        db_index=True,
                        default="OTHER",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, default="", max_length=280, verbose_name="Résumé"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Ville"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="SN", max_length=80, verbose_name="Pays"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
            ],
            options={
                "verbose_name": "Structure",
                "verbose_name_plural": "Structures",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, default="", max_length=280, verbose_name="Résumé"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="Contenu"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Date début"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date fin"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Actif"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="institution.facility",
                        verbose_name="Structure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
                "ordering": ["-created_at"],
            },
        ),
    ]
