# Generated by Django 5.2.3 on 2025-09-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
