--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ecommerce_category; Type: TABLE; Schema: public; Owner: sogentis
--

CREATE TABLE public.ecommerce_category (
    id bigint NOT NULL,
    is_active boolean NOT NULL,
    "order" integer NOT NULL,
    parent_id bigint,
    CONSTRAINT ecommerce_category_order_check CHECK (("order" >= 0))
);


ALTER TABLE public.ecommerce_category OWNER TO sogentis;

--
-- Name: ecommerce_category_id_seq; Type: SEQUENCE; Schema: public; Owner: sogentis
--

ALTER TABLE public.ecommerce_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecommerce_category_translation; Type: TABLE; Schema: public; Owner: sogentis
--

CREATE TABLE public.ecommerce_category_translation (
    id bigint NOT NULL,
    language_code character varying(15) NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(220) NOT NULL,
    description text NOT NULL,
    master_id bigint
);


ALTER TABLE public.ecommerce_category_translation OWNER TO sogentis;

--
-- Name: ecommerce_category_translation_id_seq; Type: SEQUENCE; Schema: public; Owner: sogentis
--

ALTER TABLE public.ecommerce_category_translation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_category_translation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecommerce_category ecommerce_category_pkey; Type: CONSTRAINT; Schema: public; Owner: sogentis
--

ALTER TABLE ONLY public.ecommerce_category
    ADD CONSTRAINT ecommerce_category_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_category_translation ecommerce_category_trans_language_code_master_id_5e812cf1_uniq; Type: CONSTRAINT; Schema: public; Owner: sogentis
--

ALTER TABLE ONLY public.ecommerce_category_translation
    ADD CONSTRAINT ecommerce_category_trans_language_code_master_id_5e812cf1_uniq UNIQUE (language_code, master_id);


--
-- Name: ecommerce_category_translation ecommerce_category_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: sogentis
--

ALTER TABLE ONLY public.ecommerce_category_translation
    ADD CONSTRAINT ecommerce_category_translation_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_category_parent_id_2e808295; Type: INDEX; Schema: public; Owner: sogentis
--

CREATE INDEX ecommerce_category_parent_id_2e808295 ON public.ecommerce_category USING btree (parent_id);


--
-- Name: ecommerce_category_translation_language_code_39911a53; Type: INDEX; Schema: public; Owner: sogentis
--

CREATE INDEX ecommerce_category_translation_language_code_39911a53 ON public.ecommerce_category_translation USING btree (language_code);


--
-- Name: ecommerce_category_translation_language_code_39911a53_like; Type: INDEX; Schema: public; Owner: sogentis
--

CREATE INDEX ecommerce_category_translation_language_code_39911a53_like ON public.ecommerce_category_translation USING btree (language_code varchar_pattern_ops);


--
-- Name: ecommerce_category_translation_master_id_fe6e0d92; Type: INDEX; Schema: public; Owner: sogentis
--

CREATE INDEX ecommerce_category_translation_master_id_fe6e0d92 ON public.ecommerce_category_translation USING btree (master_id);


--
-- Name: ecommerce_category_translation_slug_b166815e; Type: INDEX; Schema: public; Owner: sogentis
--

CREATE INDEX ecommerce_category_translation_slug_b166815e ON public.ecommerce_category_translation USING btree (slug);


--
-- Name: ecommerce_category_translation_slug_b166815e_like; Type: INDEX; Schema: public; Owner: sogentis
--

CREATE INDEX ecommerce_category_translation_slug_b166815e_like ON public.ecommerce_category_translation USING btree (slug varchar_pattern_ops);


--
-- Name: ecommerce_category ecommerce_category_parent_id_2e808295_fk_ecommerce_category_id; Type: FK CONSTRAINT; Schema: public; Owner: sogentis
--

ALTER TABLE ONLY public.ecommerce_category
    ADD CONSTRAINT ecommerce_category_parent_id_2e808295_fk_ecommerce_category_id FOREIGN KEY (parent_id) REFERENCES public.ecommerce_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_category_translation ecommerce_category_t_master_id_fe6e0d92_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: sogentis
--

ALTER TABLE ONLY public.ecommerce_category_translation
    ADD CONSTRAINT ecommerce_category_t_master_id_fe6e0d92_fk_ecommerce FOREIGN KEY (master_id) REFERENCES public.ecommerce_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

