--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ecommerce_product_translation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ecommerce_product_translation (
    id bigint NOT NULL,
    language_code character varying(15) NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(260) NOT NULL,
    short_description character varying(500) NOT NULL,
    description text NOT NULL,
    master_id bigint
);


--
-- Name: ecommerce_product_translation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ecommerce_product_translation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_product_translation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecommerce_productimage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ecommerce_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    alt_text character varying(255) NOT NULL,
    is_main boolean NOT NULL,
    product_id bigint NOT NULL
);


--
-- Name: ecommerce_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ecommerce_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ecommerce_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ecommerce_product_translation ecommerce_product_transl_language_code_master_id_9b57279a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ecommerce_product_translation
    ADD CONSTRAINT ecommerce_product_transl_language_code_master_id_9b57279a_uniq UNIQUE (language_code, master_id);


--
-- Name: ecommerce_product_translation ecommerce_product_translation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ecommerce_product_translation
    ADD CONSTRAINT ecommerce_product_translation_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_productimage ecommerce_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ecommerce_productimage
    ADD CONSTRAINT ecommerce_productimage_pkey PRIMARY KEY (id);


--
-- Name: ecommerce_product_translation_language_code_9613539f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ecommerce_product_translation_language_code_9613539f ON public.ecommerce_product_translation USING btree (language_code);


--
-- Name: ecommerce_product_translation_language_code_9613539f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ecommerce_product_translation_language_code_9613539f_like ON public.ecommerce_product_translation USING btree (language_code varchar_pattern_ops);


--
-- Name: ecommerce_product_translation_master_id_3207b679; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ecommerce_product_translation_master_id_3207b679 ON public.ecommerce_product_translation USING btree (master_id);


--
-- Name: ecommerce_product_translation_slug_2cc8871e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ecommerce_product_translation_slug_2cc8871e ON public.ecommerce_product_translation USING btree (slug);


--
-- Name: ecommerce_product_translation_slug_2cc8871e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ecommerce_product_translation_slug_2cc8871e_like ON public.ecommerce_product_translation USING btree (slug varchar_pattern_ops);


--
-- Name: ecommerce_productimage_product_id_fb355be3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ecommerce_productimage_product_id_fb355be3 ON public.ecommerce_productimage USING btree (product_id);


--
-- Name: ecommerce_product_translation ecommerce_product_tr_master_id_3207b679_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ecommerce_product_translation
    ADD CONSTRAINT ecommerce_product_tr_master_id_3207b679_fk_ecommerce FOREIGN KEY (master_id) REFERENCES public.ecommerce_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ecommerce_productimage ecommerce_productima_product_id_fb355be3_fk_ecommerce; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ecommerce_productimage
    ADD CONSTRAINT ecommerce_productima_product_id_fb355be3_fk_ecommerce FOREIGN KEY (product_id) REFERENCES public.ecommerce_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

