# Generated by Django 5.2.3 on 2026-01-18 14:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_app",
                    models.CharField(
                        blank=True,
                        help_text="App label of source model",
                        max_length=100,
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        blank=True, help_text="Model name of source", max_length=100
                    ),
                ),
                (
                    "object_id",
                    models.BigIntegerField(
                        blank=True, help_text="PK of the source object", null=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                ("description", models.TextField(blank=True)),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Extracted text from file (if any)"
                    ),
                ),
                (
                    "file_url",
                    models.CharField(
                        blank=True, help_text="Path or URL to file", max_length=1000
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purchase_counter", models.IntegerField(default=0)),
                ("download_tokens", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["title"], name="search_inde_title_cd0eec_idx"),
                    models.Index(
                        fields=["created_at"], name="search_inde_created_40fc25_idx"
                    ),
                ],
            },
        ),
    ]
